### ISSUE TITLE
Immersive Mode: Action Bar disappears even when Overflow is open

### ISSUE THREAD

**Issue by ReggX** [calvinaquino/LNReader-Android#115]
**Steps to reproduce:**
1. Enable Fullscreen on an immersive mode capable device (Android 4.4 or greater)
2. Open any novel content and swipe the top to show the Action Bar
3. Click on the Action Overflow Button

**Actual behaviour:** App automatically goes back into immersive mode after a short duration
**Desirable behaviour:** App waits until Action Overflow is closed before going back into immersive mode.

**Comment by Nandaka** [comment]
handled in #199 v1.1.33-beta1
