### ISSUE TITLE
Horizontal scroll toggle

### ISSUE THREAD

**Issue by firespike8** [calvinaquino/LNReader-Android#129]
Hello, I love the app but have an idea for an enhancement. I like the ability to zoom in and use text-reflow, but when I zoom in it does not change the size of the cover image. The problem with this is that the page stays as large as the cover when I zoom in, rather than constraining to the new size of the text. The problem then is that there is empty horizontal space that shouldn't be there. When scrolling down I often accidently shift the page to the side.

There are 3 possible fixes to this:
1. Button toggle to lock/unlock horizontal scroll. This would be very useful.
2. Option to make images "fit to zoom"
3. Option to change font size.

**Comment by Nandaka** [comment]
Item 1: the text should be reflow to prevent horizontal scrolling, but in some cases it might be not working (depending on how baka tsuki set the layout, e.g. using <pre>).
Item 2: existing will only zoom to width.
Item 3: you can control by zooming.
