### ISSUE TITLE
wrong aspect ratio and small resolution of covers

### ISSUE THREAD

**Issue by Mithgol** [calvinaquino/LNReader-Android#174]
The page https://www.baka-tsuki.org/project/index.php?title=Gekkou currently presents the following image of the cover:

![(cover)](https://cloud.githubusercontent.com/assets/1088720/5567042/fa82b926-8f4b-11e4-8298-41b4f3baa393.jpg)

BakaReader EX displays the following image of the cover:

![(screenshot)](https://cloud.githubusercontent.com/assets/1088720/5567027/627fe70c-8f4b-11e4-9709-9753e2383fd6.png)

Two improvements are possible:

* Currently the image looks distorted because its aspect ratio is wrong. BakaReader EX could use the cover's original aspect ratio.

* A thumbnail (small resolution image) from the page https://www.baka-tsuki.org/project/index.php?title=Gekkou is used. For better look on FullHD smartphones, full version of the image could be downloaded, such as https://www.baka-tsuki.org/project/images/1/1c/Gekkou.jpg for the above example. (This improvement might be switched off by default for the people with low bandwidth or costly traffic.)

**Comment by Mithgol** [comment]
The aspect ratio is now correct in version 1.1.25 (20150110).

The resolution is still small.

**Comment by Nandaka** [comment]
Try: http://www.mediafire.com/download/3734cc0dzzpkkft/BakaReader-EX-1.1.26-beta1.apk

**Comment by Mithgol** [comment]
I am reluctant to install a beta version from the phone's file system because it seems to be treated as a separate application and Google Play ceases to report the updates to the release published in Google Play.

You probably should just release it to Google Play if everything works as planned on your side.

**Comment by Nandaka** [comment]
Up, sorry for late release. On vacation :smile:

**Comment by Mithgol** [comment]
I've noticed that a refresh of the chapter list is not enough, I also have to leave the novel (for example, press “Back” to quit to the “Light Novel Lists”) and then reopen the novel, only then the new cover appears.

Other than that, the high-res covers look **awesome** on my FullHD mobile screen.

Thanks fo this improvement.

**Comment by Mithgol** [comment]
The above mentioned problem with refreshing of the chapter list is (most likely) a separate issue (#177).
