### ISSUE TITLE
problems with pics/illustrations

### ISSUE THREAD

**Issue by Kuroganekai** [calvinaquino/LNReader-Android#178]
i dont know why but some day the pics broke/corrupted,i tried re-download the serie, but no sign of sucess, so i deleted the entire save file and downloaded again and no sucess again,someone knows how i can solve the problem?
some screenshots:
http://prntscr.com/6abwkb

**Comment by Nandaka** [comment]
what is the novel an chapter name?

**Comment by Kuroganekai** [comment]
mondaiji tachi isekai kuru desu yo vol 4 ch 3, but it happens to ALL series,i just printscreen those since i was reading it at moment

**Comment by aahmyu** [comment]
Same problem here. Every pic is broken and doesn't shows up in the novel. And now it seems the app won't work without enabling https it keeps throwing exceptions when https is disabled it was working fine a few days ago :(

**Comment by Kuroganekai** [comment]
@aahmyu 
try clear the Datebase,and go to your photoview and delete ALL LN illustrations,and re-downlaod your series and go to settings-->reading layout and enable the option "show images".
this worked for me
