### ISSUE TITLE
error connection

### ISSUE THREAD

**Issue by conrad5291** [calvinaquino/LNReader-Android#179]
When tried update the connection to bakareader ex refused to connect causing cannot updated the novel

**Comment by Nandaka** [comment]
Can you open the website on browser?

On Tue, Mar 3, 2015 at 10:44 AM, conrad5291 <notifications@github.com>
wrote:

> When tried update the connection to bakareader ex refused to connect
> causing cannot updated the novel
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/calvinaquino/LNReader-Android/issues/179>.
>



-- 
My Blog at http://nandaka.wordpress.com
