### ISSUE TITLE
the list of teaser projects does not seem to be updating

### ISSUE THREAD

**Issue by Mithgol** [calvinaquino/LNReader-Android#184]
Two hours ago I run an update (Settings → Update and Notification → Update Now!); however, in Light Novels → TEASER section there's no entry for “Saenai Heroine no Sodatekata”, though the page http://www.baka-tsuki.org/project/?oldid=426772 seems to indicate that this LN has been given teaser status since the middle of March.

**Comment by Nandaka** [comment]
most likely because of the pages is moved from Category:Teasers to Category:Teaser_(English).

See: https://github.com/calvinaquino/LNReader-Android/blob/master/app/src/main/java/com/erakk/lnreader/Constants.java#L148

I'll update on the next release

**Comment by Mithgol** [comment]
Ok :+1:

**Comment by Mithgol** [comment]
Having installed the newest reader's version (1.1.28b, 201504120), I tried to run an update (Settings → Update and Notification → Update Now!), and it seemed to complete successfully, but the “Teaser” list remained blank.

However, when I used the “Refresh” menu item in that list, the list of teasers was repopulated correctly in the reader, and even the previously favourited (starred) light novels were remembered by Baka-Reader correctly.

Is it good enough? Or should I still have some worries about further updates of that list of teasers?

**Comment by Nandaka** [comment]
You need to manually refresh the teaser list to re-sync the pages to the correct category. 

This is by design due to the modeling of wiki page in the app, sorry about that.

**Comment by Mithgol** [comment]
Okay, thank you for explaining.
