### ISSUE TITLE
Error Updating Novel

### ISSUE THREAD

**Issue by creamflakes** [calvinaquino/LNReader-Android#185]
class.org.jsoup.httpstatusexception: http error fetching url

this problem appeared yesterday , april 6, 2015 .
it seems fine before april 6 but now i'm getting this error while i'm trying to update for a new chapter of a novel (Example. Mondaiji, Tokyo Ravens and all).

**Comment by creamflakes** [comment]
this problem appeared yesterday , april 6, 2015 .
it seems fine before april 6 but now i'm getting this error while i'm trying to update for a new chapter of a novel (Example. Mondaiji, Tokyo Ravens and all).

**Comment by Nandaka** [comment]
Can you open the website from your device?

**Comment by creamflakes** [comment]
its ok now , i just checked the Use HTTPS option .
somehow the settings changed without my permission .
