### ISSUE TITLE
Bitmap Empty

### ISSUE THREAD

**Issue by creamflakes** [calvinaquino/LNReader-Android#186]
i encounter another error , it says Bitmap Empty and the cover picture wont load . any idea how to fix this ?

**Comment by Nandaka** [comment]
Which novel and have you try to refresh the novel list?

**Comment by creamflakes** [comment]
all i bookmarked . absolute duo, gakuen toshi asterisk, mondaiji, tokyo ravens, and any other .

**Comment by creamflakes** [comment]
i also tried to refresh it but the cover still not loading and also saying bitmap empty .

**Comment by Nandaka** [comment]
Can you open the site? I got error 400 Bad Request in my pc and phone

**Comment by Nandaka** [comment]
Retested again by deleting the novel and redownload.

Need multiple times, as I hit http connection error for multiple times.

The image is there.
