### ISSUE TITLE
Update WebView behaviour for Android 5+ for mixed content

### ISSUE THREAD

**Issue by Nandaka** [calvinaquino/LNReader-Android#189]
android doc:
https://developer.android.com/about/versions/android-5.0-changes.html#BehaviorWebView

CODE: SELECT ALL
If your app targets API level 21 or higher:
The system blocks mixed content and third party cookies by default. To allow mixed content and third party cookies, use the setMixedContentMode() and setAcceptThirdPartyCookies() methods respectively.
The system now intelligently chooses portions of the HTML document to draw. This new default behavior helps to reduce memory footprint and increase performance. If you want to render the whole document at once, disable this optimization by calling enableSlowWholeDocumentDraw().
If your app targets API levels lower than 21: The system allows mixed content and third party cookies, and always renders the whole document at once.

**Comment by Nandaka** [comment]
```
W/class com.erakk.lnreader.helper.BakaTsukiWebChromeClient(27513):  Console: 368:Mixed Content: The page at 'https://www.baka-tsuki.org/' was loaded over HTTPS, but requested an insecure image 'file:///storage/extSdCard/Android/data/com.erakk.lnreader/files/project/images/thumb/f/fa/NT_Index_v12_000.jpg/120px-NT_Index_v12_000.jpg'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by Masclaux** [comment]
Hi 

Have you  planned to upgrade minimum api requirement ?  I try to fix scaling and probably can not be fixed below with API 8

**Comment by Nandaka** [comment]
Not yet, but maybe you can add check for the current api level? Like:

``` java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
 // do something for newer android
        }
```

There are still about 7% using gingerbread, which is around 5k+ active installation.


![](http://i.imgur.com/1KSOVkN.png)

**Comment by Masclaux** [comment]
ok ty :)
