### ISSUE TITLE
Improve volume button scroll

### ISSUE THREAD

**Issue by mrmonday56** [calvinaquino/LNReader-Android#192]
If you change the scroll to be a snapping action instead of a flinging action it would make the text much more readable while using the volume buttons to scroll.  As it is, they're basically unusable because it takes so long for the view to scroll and stop moving again.

I think the change would be in DisplayLightNovelContentActivity.java lines 483 and 487 using the pageDown/Up method of WebView or the ScrollBy method inherited from View.
http://developer.android.com/reference/android/webkit/WebView.html#pageDown(boolean)
http://developer.android.com/reference/android/view/View.html#scrollBy(int, int)

**Comment by Nandaka** [comment]
I think you can tweak the scrolling size, so it will fit to your use.
