### ISSUE TITLE
DownLoad List not clearing.

### ISSUE THREAD

**Issue by Wolfpup67** [calvinaquino/LNReader-Android#197]
the Download list not clearing after the downloads have completed.

![screenshot_2015-06-18-07-47-46 1](https://cloud.githubusercontent.com/assets/8302307/8230494/c10f52f2-158e-11e5-97f4-73fa04198d8c.png)

This is happening since the newest release.

**Comment by Nandaka** [comment]
should be fixed in https://github.com/calvinaquino/LNReader-Android/releases/tag/1.1.32-beta2
