### ISSUE TITLE
New GUI at Fullscreen

### ISSUE THREAD

**Issue by Desaroll** [calvinaquino/LNReader-Android#198]
My app updated today, and, at least in a LG F60 with fullscreen activated, the reading layout is like this:
![image](https://cloud.githubusercontent.com/assets/1253183/8235755/22d07338-15ba-11e5-8d33-b1828f5af518.png)

The upper and lower bar of Android hide correctly, but the title and the black spaces (I suppose from the app) do not dissapear. I tried:
1) Restarting the app.
2) Restarting the phone.
3) Disabling fullscreen, loading the novel, and reactivating fullscreen.
4) Toggle the "Invert Colors" (I didn't think that would work, but I tried it anyway.)

It worked correctly before the update.

Software details (In Spanish):
![image](https://cloud.githubusercontent.com/assets/1253183/8235700/c1314e36-15b9-11e5-95ab-e8e410d445ad.png)

**Comment by Nandaka** [comment]
notes for me:
https://github.com/yukuku/androidbible/blob/develop/Alkitab/src/main/java/yuku/alkitab/base/IsiActivity.java#L1214

**Comment by Nandaka** [comment]
try: https://github.com/calvinaquino/LNReader-Android/releases/tag/1.1.32-beta2

**Comment by Desaroll** [comment]
At first glance, other than the debug bar, Fullscreen shows correctly, but there's no way to access the upper menu of the app. Also if I slide up-down (As usual in previous versions to show up the top menu), the Android upper and lower bar appears. After some time, the upper one dissapears, leaving the lower one there, and the fullscreen option seems to disable itself if I go to menu and then return to the novel.

Also, when fullscreen is disabled, there's an extra space over the top menu.

First glance:
![image](https://cloud.githubusercontent.com/assets/1253183/8505852/49e5b866-21cc-11e5-830b-b3454f35a317.png)

Top-down slide:
![image](https://cloud.githubusercontent.com/assets/1253183/8505847/142b317e-21cc-11e5-8ac5-c6e72df0bf45.png)

Top bar dissapears, but lower keeps there after some time:
![image](https://cloud.githubusercontent.com/assets/1253183/8505844/027a5504-21cc-11e5-9acb-cb869815df60.png)

If I go to android's home and back to the app, or to the app's menu and back to the novel:
![image](https://cloud.githubusercontent.com/assets/1253183/8505858/70c7098a-21cc-11e5-8558-11de676815bc.png)

That upper space also appears if I manually deactivate the fullscreen mode.

I'm sorry for bringing more trouble.

**Comment by Desaroll** [comment]
Forget the part about fullscreen turning on by itself. I don't know what I did back then, it doesn't do it anymore. The extra space is still there if I turn it on manually.

**Comment by Nandaka** [comment]
merged with #199
