### ISSUE TITLE
Full screen not working in conjunction with previous/next buttons, Full screen mode not consistant.

### ISSUE THREAD

**Issue by john34404** [calvinaquino/LNReader-Android#199]
The new UI for the app is confusing/not fully working. Ok so I want my chapters displayed in full screen mode with the previous/next  buttons at the top. But I cannot get the chapters to consistently be in full screen mode.

It changes from far zoomed out mode to full screen mode only after I go into the settings. I need to do this every time for every chapter. I think its due to the newest android update. V:5.0.1

Is this a bug? Or do I need step by step instructions?

What I get without full screen mode on (and with full screen mode on after advancing to next chapter):
![screenshot_2015-06-22-05-11-18 2](https://cloud.githubusercontent.com/assets/13000657/8282842/f496bdfe-18b8-11e5-8b77-a6bd6ec11d2c.png)

What I get with full screen mode on:
![screenshot_2015-06-22-05-11-40 1](https://cloud.githubusercontent.com/assets/13000657/8282867/1d70a38e-18b9-11e5-82a8-68b50f0dbcfc.png)

What I want/expect: Received this result by turning full screen mode on, going to different chapter, turning it off than going back to previous chapter.
![screenshot_2015-06-22-05-11-25 1](https://cloud.githubusercontent.com/assets/13000657/8282833/e77ef7c6-18b8-11e5-8ec4-a2b969b387d5.png)

**Comment by john34404** [comment]
The phone is a Samsung galaxy s4 active.

**Comment by Nandaka** [comment]
There is a bug on the fullscreen mode for 1.1.31. It should not be tied to the chapter setting (except the zoom level).

But fyi, in the fullscreen mode (or immersive mode if you are using kitkat+), it should hide the action bar.

**Comment by john34404** [comment]
I have always used the bottom picture version on my device. If the bottom version was a glitch than it would be a nice setting. If it is suppose to be like the bottom version on certain settings than what are the settings?

**Comment by Nandaka** [comment]
Should be like number 3 in this page: https://developer.android.com/training/system-ui/immersive.html

**Comment by Mithgol** [comment]
I'm on HTC One M9 (running Android 5.0.2), a checkbox in on “Use Fullscreen” in “Preferences” → “Reading Layout” → “Group 2”, but the action bar does not go away.

Also, while notification bar (topmost) and software buttons bar (bottommost) disappear in fullscreen mode, the application does not seem to claim their area and it remains solid dark gray filled.

I cannot provide a screenshot because Power+Home combination requires software “Home” button that is not visible in fullscreen mode.

**Comment by Nandaka** [comment]
Try https://github.com/calvinaquino/LNReader-Android/releases/tag/1.1.32-beta2

**Comment by bliu886** [comment]
In the beta, it doesn't seem to work on my device, running Android 5.0.2. It is how Mithgol states dark grey bars where the notification bar and the software button bar are located:

![screenshot_2015-07-04-21-33-57 1](https://cloud.githubusercontent.com/assets/13091681/8509965/26273a02-2295-11e5-8de2-258f7c763503.png)

**Comment by Nandaka** [comment]
Try: https://github.com/calvinaquino/LNReader-Android/releases/tag/1.1.32-beta3

Tested in emulator (API10/Gingerbread)
![device-2015-07-05-135406](https://cloud.githubusercontent.com/assets/836867/8510505/9f2913b6-231d-11e5-8d1d-27e2e889700c.png)

On Samsung Galaxy Note (API21/Lollipop)
![device-2015-07-05-135719](https://cloud.githubusercontent.com/assets/836867/8510507/c655b32c-231d-11e5-97c2-571629c63656.png)

**Comment by jeremiejig** [comment]
Hello,

The playstore version is now 1.1.32, and while it is pretty great with all the fix, some issues appear and remain.

Pretty much all the issue has already been raised.

With this fullscreen mode, I can't find a way to change chapter (There is no more next/previous button).
Also the menu button which was with the action top bar was pretty convenient to toggle invert color, change to next or previous chapter.

I'm expecting the menu button to be at the bottom with the system nav bar like in this screenshot : 

![screenshot_2015-07-09-12-54-26](https://cloud.githubusercontent.com/assets/3978761/8593649/dea525e2-2639-11e5-93b7-ac692a210187.png)

While i'm there, here is my immersive fullscreen mode.
The app is running on a Xperia Z3 running lollipop 5.0.2.

![screenshot_2015-07-09-12-09-44](https://cloud.githubusercontent.com/assets/3978761/8593679/26003a58-263a-11e5-857e-4c44c5551123.png)

When first bringing up the activity, the android nav bar take the place but don't show the icon.
After the first action which will display the icon (like showing the android notification bar at the top), the android nav bar will remain has shown in the screenshot.

I wish you the good luck with all the fixes.

**Comment by Nandaka** [comment]
the 1st picture might be impossible, as that menu overflow icon only will visible if the application is targeting android 2.3.x

maybe I need to add virtual button to trigger menu pop-up.

**Comment by jeremiejig** [comment]
- Another approach is to make the app topbar dissappear when scrolling
down, and appear when scrolling up, *like in the tapastic app* a more
accessible example would be chrome app address bar.

- Or you can make the app topbar react like the notification status bar.
Although it might be a bit weird.

**Comment by Mithgol** [comment]
Upgraded to 1.1.32 (201507090).

On my HTC One M9, the action bar and the notification bar (on the top) both disappear just fine. (Except that action bar can't be displayed again, as @jeremiejig have previously noticed.) However, while the phone's navigational buttons (on the bottom) also disappear, the application does not seem to claim their area and it remains solid dark gray filled.

I have found a workaround:

* in the phone's “Settings” → “Personal” → “Personalize” → “Navigation bar” → “Change navigation buttons”, add “Hide navigation bar” button,

* in BakaReader EX, use that button to remove navigation buttons from the screen. The application reclaims their area then.

**Comment by Wolfpup67** [comment]
I'm also seeing this issue even with the current released version on my Samsung Galaxy Prevail LTE running Android 4.4.4. I am including a screen shot form my phone.
![screenshot_2015-07-09-17-15-00 1](https://cloud.githubusercontent.com/assets/8302307/8607902/4513ab44-2664-11e5-922f-dd3bb190eeb7.png)

**Comment by Nandaka** [comment]
> Chrome behaviour? 

You means show the toolbar when the window have focus (and disappear after few seconds)?

> unclaimed area

Maybe I need to add more flag (SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN / SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION )? 

I'm using Lollipop (CM12.1) and it shows correctly...

**Comment by Nandaka** [comment]
Try https://github.com/calvinaquino/LNReader-Android/releases/tag/1.1.33-beta1

tap to show the Toolbar, and it should auto hide after 4s.

**Comment by jeremiejig** [comment]
When I say chrome behavior, I mean the android chrome app.
When you slide to the bottom of the page the address bar will collapse
upside (hope you see what I mean), and when you need the address bar, or
simply when the user slide to the top, the address bar reappear.

**Comment by Nandaka** [comment]
I think it is better to show the toolbar when user is touch the content (not scrolling) and auto hide after few seconds.
I don't want to scroll up just to show the toolbar and slide down to hide it :smile:

**Comment by jeremiejig** [comment]
Well yeah, might depends on the person.

I tested 1.1.33-beta1 on my xperia, setting aside that I find the
apparition a bit spooky, I do have a feedback :
You need to deactivate / activate the timer when the user is clicking on
the menu button.

Well apart that I find it pretty weird with the bookmark 📑 feature, I find
this behavior pretty convenient. ☺

On a side note, the android nav bar at the bottom now correctly hide its
icons, but still do not reclaim the empty space.

I think it is better to show the toolbar when user is touch the content
(not scrolling) and auto hide after few seconds.
I don't want to scroll up just to show the toolbar and slide down to hide
it [image: :smile:]

—
Reply to this email directly or view it on GitHub
<https://github.com/calvinaquino/LNReader-Android/issues/199#issuecomment-120301849>
.

**Comment by Nandaka** [comment]
what is your android version? 

It should hide the nav bar on API19/KITKAT
https://developer.android.com/reference/android/view/View.html#SYSTEM_UI_FLAG_HIDE_NAVIGATION
https://developer.android.com/reference/android/view/View.html#SYSTEM_UI_FLAG_FULLSCREEN

Refer to https://github.com/calvinaquino/LNReader-Android/blob/master/app/src/main/java/com/erakk/lnreader/helper/DisplayNovelContentUIHelper.java#L156

**Comment by jeremiejig** [comment]
Well I'm on android 5.0.2 lollipop,

I'm seeing the use of `WindowManager.LayoutParams.FLAG_FULLSCREEN` https://github.com/calvinaquino/LNReader-Android/blob/master/app/src/main/java/com/erakk/lnreader/helper/DisplayNovelContentUIHelper.java#L155

I'm wondering if it is interfering with the `system_ui_flag` while there isn't anything in the doc that said so.

**Another point** : when the user perform an action to display the navigation bar again (like resuming the app) the navigation bar won't rehide itself (while the status bar rehide without problem, thanks to the immersive flag I think).
**Workaround for now** : tap the screen, to display the action bar, and the timer will rehide everything.


**Finally** : Now that I'm aware of the flag `SYSTEM_UI_FLAG_LAYOUT_*` you might want to set these when the user has activate the fullscreen. I think it will remove the spookiness I feel when the action bar show/hide (The redrawing taking into account the action bar I think without).

Hope I'm readable.

**Comment by Nandaka** [comment]
implement timer to automatically hide after 10s.

another way is by fast scrolling either direction will force the action bar to be hidden
