### ISSUE TITLE
Horizontal Orientation Lock only works in Setting screen

### ISSUE THREAD

**Issue by DragonSaber** [calvinaquino/LNReader-Android#200]
Setting the Orientation lock to Horizontal only changes the Setting screen to be horizontal layout.  All other screens are using the system orientation.  

Steps:
1) Set the phone orientation to portrait.
2) Changed to horizontal lock In the app: Setting -> General -> Orientation Lock: Horizontal
3) Go to any other screen and observe that the orientation is not horizontal lock. 

Spec:
App version: 1.1.31
Phone: Nexus 4: 5.0.1

**Comment by Nandaka** [comment]
try https://github.com/calvinaquino/LNReader-Android/releases/tag/1.1.32-beta2
