### ISSUE TITLE
scrolling bug in a chapter

### ISSUE THREAD

**Issue by bliu886** [calvinaquino/LNReader-Android#201]
In a chapter, pressing the back button while scrolling and then pressing the back button while scrolling on the novel list causes the very first page to be set to the novel list. This causes an "image" of the novel list to appear over the screen.

Steps to reproduce:
1)   Open BakaReader EX
2)   select Light novels
3)   select any light novel in the list that has chapters not in an external link
4)   select a chapter
5)   while continuously scrolling up and down, hit the back button
6)   while continuously scrolling up and down, hit the back button again

Here is a link to a video demonstration of this:
https://drive.google.com/file/d/0B2G_jPctxVodd05HWGhnbkg0cVk/view?usp=sharing

repeatedly pressing the back button causes this error to fix itself somehow.

**Comment by Nandaka** [comment]
try: https://github.com/calvinaquino/LNReader-Android/releases/tag/1.1.32-beta2

**Comment by Nandaka** [comment]
Updated: https://github.com/calvinaquino/LNReader-Android/releases/tag/1.1.32-beta3
