### ISSUE TITLE
Default Font Size/Zoom Level

### ISSUE THREAD

**Issue by devildragin** [calvinaquino/LNReader-Android#202]
Latest version appears to not scale the page very well, if I delete the cache in a previously downloaded chapter and redownload, the resulting chapter looks super zoomed out with tiny text and thumbnails.

**Comment by Nandaka** [comment]
notes for me: http://stackoverflow.com/questions/10583871/setting-webview-zoom-based-upon-screensize

**Comment by devildragin** [comment]
The default zoom level works fine in 1.1.30 (had a helluva time finding a copy) which is the immediate previous version, in case this helps at all. I have this issue on both a Note 4 and a Note 10.1 2014.

**Comment by Mithgol** [comment]
I have this issue on HTC One M9. It leads me to believe that the issue's more or less universal.

(While I am at it, I'm admitting I also haven't had this problem in the previous version.)

**Comment by Nandaka** [comment]
most likely because I update the target api to lollipop, which changes the behaviour for WebView.

I'll change the default zoom based on the density.

**Comment by Nandaka** [comment]
Try: https://github.com/calvinaquino/LNReader-Android/releases/tag/1.1.32-beta3

now setting the default zoom based on screen density:
default: 100%
hdpi:150%
xhdpi:200%
xxhdpi:300%

please reopen if you have another default
