### ISSUE TITLE
Reemergence of issue #177 on 1.1.33-beta1+

### ISSUE THREAD

**Issue by yaminorito** [calvinaquino/LNReader-Android#204]
Issue #177(Novel Chapter List doesn't refresh) reemerged on new UI.
On my oldies:
4.0.4: not working
4.2.2: not working
4.4.2: delayed, arnd 500ms~2s.

**Comment by Nandaka** [comment]
weird, I didn't change the listing logic, may need double check.

as for delay, I think it is normal if you have big DB

**Comment by yaminorito** [comment]
Further tests: 
It only works properly when next button is used after finishing a chapter.

**Comment by Nandaka** [comment]
also weird, cos the next button doesn't create any callback to the previous activity.

worst case scenario, I'll just put a refresh when the chapter listing is resumed.

**Comment by Nandaka** [comment]
Try: https://github.com/calvinaquino/LNReader-Android/releases/tag/1.1.34-beta1

**Comment by yaminorito** [comment]
Working now. Thanks! I'll be closing this issue.
