### ISSUE TITLE
ActionBar hides first few lines

### ISSUE THREAD

**Issue by akrolsmir** [calvinaquino/LNReader-Android#208]
The ActionBar on the latest version of Bakareader Ex hides the first few lines of content, even when scrolled all the way up. Picture (this is on Nexus 5, Android Lollipop 5.1.1.):

![2015-07-27 23 15 28](https://cloud.githubusercontent.com/assets/856034/8920410/7a787f40-347d-11e5-9a79-d09883fc5e14.png)

**Comment by Nandaka** [comment]
Try to enable fullscreen for the time being.

**Comment by Nandaka** [comment]
https://github.com/calvinaquino/LNReader-Android/releases/tag/1.1.34-beta1

**Comment by akrolsmir** [comment]
The main issue is fixed (assuming the bar on top is just a debug thing). However, when I toggle fullscreen and then tap to bring up the actionbar, the actionbar hides the first few lines again.

![2015-07-28 17 40 26](https://cloud.githubusercontent.com/assets/856034/8938782/89a8c4fa-3515-11e5-89cd-4a2e525cee1e.png)
![2015-07-28 17 40 53](https://cloud.githubusercontent.com/assets/856034/8938780/881b21e6-3515-11e5-880c-744888baf662.png)

**Comment by Nandaka** [comment]
The greybox is debug thing, as for full screen mode, it will hide the first few line when the action bar shown (by design). It should be OK as the action bar will auto hide after few seconds.

For normal mode, it will not hide the first few lines (always below action bar).
