### ISSUE TITLE
Trouble when loading Novel pages with more chapters in them

### ISSUE THREAD

**Issue by ShadowfoxEX** [calvinaquino/LNReader-Android#209]
When I try to move between chapters, the time it takes to load each one becomes noticeably longer after each chapter. After 3-5 chapters, I get a notification that the app isnt responding and asked if I should close it. I go to a chapter, come back to the novel page, and then to a different chapter, etc

**Comment by ShadowfoxEX** [comment]
I'm just realizing that it might be the same problem as #206

**Comment by Nandaka** [comment]
#206 is caused from the zoom button is still shown in the webview when the actiivity closed. Now I disable the button visibility, it doesn't happen anymore.

Must be something else.

**Comment by yaminorito** [comment]
I tried monitoring memory usage of the app on 4.2.2 phone using Android Studio, seems fine to me, the fluctuations are fine with no drastic memory allocation increase. What version of android are you using?

**Comment by ShadowfoxEX** [comment]
5.0.2. I cant actually see what's causing it, I dont always seem to recreate the problem, I think it might be more of a memory overflow than a memory leak, maybe with the novels that have 100+ chapters. But it occasionally happens otherwise

**Comment by Nandaka** [comment]
is the chapter got animated gif on it?

**Comment by ShadowfoxEX** [comment]
They have those?

**Comment by ShadowfoxEX** [comment]
No, i dont think it does, it's not limited to one chapter, it's more like specific novels. Though the crashes dont always seem to happen. I cant actually see where the resources are, so I dont know what's causing them anymore.

**Comment by Nandaka** [comment]
which one?

**Comment by ShadowfoxEX** [comment]
Okay, I'm sure of it now, novels with more chapters are more likely to crash the app, namely Tate no Yuusha no Nariagari, which as 700+ chapters. I've timed ones with fewer chapters and ended up with half a second, more chapters 2-3, tate no yuusha 5-8 seconds or a crash. Others crash as well but tate no yuusha is the worst of them

**Comment by ShadowfoxEX** [comment]
Yeah... It's probably an overload error rather than a memory leak. My phone's pretty shit, though it doesn't seem to happen on other phones (my friend's) with anything other than tate no yuusha

**Comment by Nandaka** [comment]
Uploaded new version: https://github.com/calvinaquino/LNReader-Android/releases/tag/1.1.35-beta1

If it still happens, can you upload the log file?

**Comment by ShadowfoxEX** [comment]
Okay, downloaded the updated version off googleplay and it's much better now. Doesnt crash at all and the novel chapters list loads in less than half the time. 1-2 seconds

**Comment by ShadowfoxEX** [comment]
Now, how do I mark this as resolved
