### ISSUE TITLE
Reaching End of Chapter Doesn't Mark as Read 

### ISSUE THREAD

**Issue by devildragin** [calvinaquino/LNReader-Android#210]

**Comment by devildragin** [comment]
Damn phone keyboards, chapters are no longer marked as read after reaching the end.

**Comment by Nandaka** [comment]
which chapter is it?

**Comment by devildragin** [comment]
It feels like any chapter, for the sake of showing an example: Magika no Kenshi to Shoukan Maou volume 4 chapter 1. I tested clearing read marker on previous read ones and 're-reading' it and it leaves it as unmarked.

**Comment by Nandaka** [comment]
Make sure you are scrolling until the end of the page.
If still not working, can you get the adb log? 
Check http://forum.xda-developers.com/showthread.php?t=1726238 for details.

**Comment by devildragin** [comment]
I'll try to see if I can get you one after I get home, I take it the best
method is to use adb from my PC as the Catlog application does not seem to
work without root on 5.0.1. Checked my tablet (4.4.2) does not appear to
have this issue.

**Comment by devildragin** [comment]
I have an adb log. All i did was run adb logcat, open a chapter/section, scroll to the bottom, and hit the back button. Is there a way that you want me to send it to you?

**Comment by Nandaka** [comment]
Put it to pastebin, or paste it directly here

**Comment by devildragin** [comment]
Is there a way to filter down the logcat for you, the file I have is 2.3MB and pastebin/github won't accept that much text.

**Comment by Mithgol** [comment]
If I were you, I'd try [7-Zip](http://www.7-zip.org/) in Ultra compression mode.

**Comment by devildragin** [comment]
https://drive.google.com/file/d/0B6eCqZt27963eDVIQXliSEQwVGc/view?usp=sharing

Nandaka see if the above link works for you, message me when you are done with it so I can remove the file.

**Comment by Nandaka** [comment]
got it.

**Comment by Nandaka** [comment]
Looks like the reported Y position doesn't match with the content height...
Do you scroll all the way to the bottom page?

https://github.com/calvinaquino/LNReader-Android/blob/master/app/src/main/java/com/erakk/lnreader/UI/activity/DisplayLightNovelContentActivity.java#L595

**Comment by devildragin** [comment]
Yea, I hit the bottom then 'kept trying to scroll down' just to be sure.

**Comment by devildragin** [comment]
The latest release appears to address the issue, chapters on my Note 4 are marked read after I hit the bottom like they used to.
