### ISSUE TITLE
Volume 7.5 of “Rokujouma no Shinryakusha!?” is not detected

### ISSUE THREAD

**Issue by Mithgol** [calvinaquino/LNReader-Android#211]
Hitting the “REFRESH CHAPTER LIST” does not seem to reflect the recent appearance of Volume 7.5 on the page of “Rokujouma no Shinryakusha!?”, even after I have made [that](http://www.baka-tsuki.org/project/index.php?diff=456582) and [that](http://www.baka-tsuki.org/project/index.php?diff=456583) change on the page.

**Comment by Nandaka** [comment]
Most likely because of the sub-title below the volume marker, other volumes doesn't have it:
![image](https://cloud.githubusercontent.com/assets/836867/9402105/bd9921b6-480b-11e5-9a7c-514cf7c999eb.png)

Ask them to merge the subtitle with the volume marker, e.g.: ```Volume 7.5: The Blue Knight and The Silver Princess side story```

**Comment by Nandaka** [comment]
ah, ignore the previous message....

It is loaded in my device, I think someone update the layout.

**Comment by Mithgol** [comment]
It seems that my changes weren't immediately applied for some reason.

Anyway, now the issue's gone.
