### ISSUE TITLE
App doesn't see any of the files.

### ISSUE THREAD

**Issue by Aradeid** [calvinaquino/LNReader-Android#212]
I don't have internet access all the time so I usually download 2-5 weeks worth of novels. Lately howether the app would suddenly start ignoring the database, all the lists, the settings, and the backups, despite them all still being present as files. Last time this happened I just re-downloaded all my novels, bt this time I won't be having internet access for my phone for another 1 or 2 months so I'd like to find a better solution than re-stocking.

Android v.4.1.2 Jelly Beans

**Comment by Nandaka** [comment]
Even after restoring the backup? Are you using any kind of antivirus? 
Where do you store the DB? Is it on SD Card?

Can you get the log file? See http://forum.xda-developers.com/showthread.php?t=1726238
