### ISSUE TITLE
App not loading any novel after it finish "downloading"

### ISSUE THREAD

**Issue by Goodiehao** [calvinaquino/LNReader-Android#216]
as stated. they gave me some exceptional handling or null pointer

**Comment by Nandaka** [comment]
can you give me the novel name and more details (such as log file)?

**Comment by Goodiehao** [comment]
As in the attached file. That the error i get for any novel i chose

**Comment by Nandaka** [comment]
your attachment is not uploaded to github, you may need to upload it to mediafire/pastebin.

Are you using the latest version: https://github.com/calvinaquino/LNReader-Android/releases/tag/1.1.36

Also, are you using firewall/antivirus in your phone? try to turn it off first.

**Comment by Goodiehao** [comment]
hi as requested to upload the image file here.
![screenshot_2015-11-04-17-57-27](https://cloud.githubusercontent.com/assets/15606971/10963319/7bb7bd06-83da-11e5-8562-d4d2afa95e50.png)

**Comment by Nandaka** [comment]
looks like your DB is not upgraded, try to restore old backup and restart the application?

**Comment by Goodiehao** [comment]
I did not set any backup. Any idea what to do then?

**Comment by Nandaka** [comment]
Wait for the application to be updated. I've uploaded new version.
