### ISSUE TITLE
There is a large space betwenn words

### ISSUE THREAD

**Issue by s5706820** [calvinaquino/LNReader-Android#218]
I had open kitkat zoom fix already but it didnt work.
How to solve it??
![screenshot_2015-11-04-22-47-15](https://cloud.githubusercontent.com/assets/15662227/10956601/70501530-838f-11e5-832d-3db69c01029a.png)

**Comment by Nandaka** [comment]
Go to Settings -> Reading Layout -> CSS Layout (on the bottom).

Set Force Justified = False.

**Comment by s5706820** [comment]
oh thank you,  I done it already once but i  didnt restart the app so it didnt take effect. but now it is work. thank you
