### ISSUE TITLE
feature request: ignore EXTERNAL LINK updates unless URL changes

### ISSUE THREAD

**Issue by Mithgol** [calvinaquino/LNReader-Android#219]
What is the problem?

The problem is, if I click on “Update now!” more or less frequently, i.e. daily (or weekly), then after each update I see a few titles of new or updated chapters that reside directly on “Baka-tsuki” and then **literally hundreds** of “Updated Chapter” messages from EXTERNAL LINK chapters.

And it's not like these external chapters **really** are daily (or weekly) updated in hundreds. They are actually just hosted on sites that use engines that generate pages on-the-fly (such as Wordpress engine) with new banners, new voting blocks, new (randomly chosen) colorful page headers, and then new (current) datetime headers that force web browsers to refrain from using any old (cached) versions of those web pages.

Any real updates become totally buried in these hundreds of (mostly false) messages of updated external chapters.

Therefore I need a new option that would force BakaReader EX to **completely ignore** updates of EXTERNAL LINK chapters (unless something exceptional, such as an URL change, happens). This option should also prevent BakaReader EX from querying external sites for dates of pages (and thus should greatly reduce the time that “Update Now!” spends from its start to its finish).

**Comment by Nandaka** [comment]
Try Settings -> Update and Notification -> Include External Chapter = False?

If the url changes, most likely it will detected as new chapter instead, cos no wiki id I can use to check whether this is new chapter or not.

**Comment by Mithgol** [comment]
Thanks. (I have totally forgotten that existing “Include external chapter” setting, sorry.)

**Comment by Mithgol** [comment]
Reopening.

I have an impression that, while unchecking “Include External Chapter” indeed ceases messages about new (=updated) external chapters, it also shuts down messages about any appearance of new (=previously nonexistent) external chapters.

Is that impression correct?

**Comment by Mithgol** [comment]
No, that impression is not correct.

Some chapters just appeared on http://saekanothetranslation.wordpress.com/ before they were referenced from Baka-Tsuki.

I now see them in BakaReader EX as “New Chapter” / “EXTERNAL LINK” entries as well.

This issue can now be closed.
