### ISSUE TITLE
External chapters are marked as downloaded when tried to download via context menu

### ISSUE THREAD

**Issue by HYBRID-BEING** [calvinaquino/LNReader-Android#221]
~~Download All Chapters button ignores external chapters and there doesn't seem to be any option to change that. I have to resort to downloading volumes one by one.~~
UPD: actually, disregard that, i got it wrong. Download All Chapters silently ignores external chapters, and volume and chapter download marks external chapters as downloaded, yet they are actually not and only get downloaded after opening them (if internet connection is up).

**Comment by Nandaka** [comment]
that is by design, as I don't know how to download the external link with all the related resources (e.g. css, js, images, etc). 

The external pages only saved when you load it manually using API provided by WebView.

**Comment by HYBRID-BEING** [comment]
Oh well, can't be helped then. In this case, perhaps, chapters should not be marked as downloaded, when trying to download them or whole volume.

**Comment by Nandaka** [comment]
welp, that's a bug then. I'll fix it so it will skip the external chapter.
