### ISSUE TITLE
Resize Cover is not working correctly

### ISSUE THREAD

**Issue by HYBRID-BEING** [calvinaquino/LNReader-Android#223]
With "Resize Cover" option off cover is still resized to fit the screen (at least by width), but it will have a huge vertical padding (most likely enough to fit original cover by height).
Example: Rune Troopers.

**Comment by Nandaka** [comment]
do you also enable 'Use Hi-Res Cover? I suspect because the height is not resized if the image is larger than the available screen.

**Comment by HYBRID-BEING** [comment]
Indeed. I'm not sure if the size with "Use Hi-Res Cover" off is correct or not, but with "Use Hi-Res Cover" on there is definitely extra padding.
