### ISSUE TITLE
Custom Color for Table Border not working

### ISSUE THREAD

**Issue by panduutama** [calvinaquino/LNReader-Android#224]
Color of table border stay black after change it to brighter color. Only encounter at navigation table, not sure if it happen too in novel content.

**Comment by Nandaka** [comment]
can you give me the novel to check?

**Comment by panduutama** [comment]
CtG Volume 1 Chapter 1, all of table border are black.
Make sure to enable custom color to encounter this trouble.

**Comment by panduutama** [comment]
Sorry, there are only two table which are noticeable, first one and navigation table.

**Comment by panduutama** [comment]
Border color changed on illustrations page.

**Comment by Nandaka** [comment]
The Table of Content and prologue are not using table, but div.
![image](https://cloud.githubusercontent.com/assets/836867/13203030/06fbf4b0-d8e8-11e5-8349-082acda2e6e3.png)
![image](https://cloud.githubusercontent.com/assets/836867/13203048/7d6e233e-d8e8-11e5-8795-93ccb7b30e31.png)


but the quest one, maybe I can force it to follow the color defined in the settings.
![image](https://cloud.githubusercontent.com/assets/836867/13203038/46755104-d8e8-11e5-8fd9-92a565d56fb2.png)

**Comment by panduutama** [comment]
Ah, that's why the color is not changed. (Already figure out it's div, not table actually)

Actually, what I mean is this.
![screenshot_2016-02-21-22-41-36_com erakk lnreader](https://cloud.githubusercontent.com/assets/17326488/13203182/076affb8-d8ed-11e5-999f-24cb982725f8.png)
Before I enabled custom color settings, the color is white. What I suspect is (become black in custom color) it caused by Color Invert feature.
![screenshot_2016-02-21-22-42-24_com erakk lnreader](https://cloud.githubusercontent.com/assets/17326488/13203219/f9c0eade-d8ed-11e5-8c40-d0c86932fe3d.png)
The original border color is black, and it's div not table. But, can you do something about that? If can't, it can't be helped.

**Comment by Nandaka** [comment]
I can replace it, but it will affect all table border because the navigation menu doesn't have specific class/id.. Is it OK?

Refer to: https://github.com/calvinaquino/LNReader-Android/blob/master/app/src/main/res/raw/style_custom_color.css#L184
![image](https://cloud.githubusercontent.com/assets/836867/13209123/1a20cec6-d95b-11e5-8bbe-714308f014c3.png)

**Comment by panduutama** [comment]
Actually, I'm not familiar with css html stuffs. I'm leave this to you.

Thank You.
