### ISSUE TITLE
Having difficult to bookmark some line

### ISSUE THREAD

**Issue by ghost** [calvinaquino/LNReader-Android#225]
Having difficult to bookmark line when text is in italic (not sure for bold and/or underlined text), but still can bookmark the line by pressing / touch free space after end of the text.

**Comment by Nandaka** [comment]
Can you give me the sample line (including chapters) ?

**Comment by Nandaka** [comment]
![image](https://cloud.githubusercontent.com/assets/836867/13212528/e6b6a62e-d97c-11e5-9d65-fd5c64463b58.png)

some lines cannot be bookmarked, as it doesn't use the <p> tag.

**Comment by panduutama** [comment]
![screenshot from 2016-02-22 17 05 47](https://cloud.githubusercontent.com/assets/17326488/13213823/8a0349fa-d986-11e5-92a6-1f5201b5dc57.png)

In this line, you can't bookmark it by touching <i>hybird</i> and <i>pure-blooded</i>

![screenshot from 2016-02-22 17 13 15](https://cloud.githubusercontent.com/assets/17326488/13214037/110ca648-d988-11e5-8d10-c2f6f990b9d5.png)

![screenshot_2016-02-22-17-11-12_com erakk lnreader_1456132339418](https://cloud.githubusercontent.com/assets/17326488/13214061/3a5def48-d988-11e5-84a2-264017306608.jpg)
![screenshot_2016-02-22-17-11-14_com erakk lnreader_1456132367938](https://cloud.githubusercontent.com/assets/17326488/13214063/3c9e8e2a-d988-11e5-8fe8-5364918a9c07.jpg)

And in this line, you can bookmark it by touching on red area (and small gap) but the text can't.

**Comment by Nandaka** [comment]
most likely due to no event bubbling handler in the js from the &lt;i&gt; tag in the &lt;[&gt;

need to find a way to do it in pure js
