### ISSUE TITLE
Missing chapters are not replaced with the new chapters of the same name

### ISSUE THREAD

**Issue by Mithgol** [calvinaquino/LNReader-Android#226]
I have the “Show Missing Chapters” checked in “Settings → General” and I've noticed that such missing chapters are not **replaced** when the new chapters appear to have the same name. They coexist.

The result looks like the following:

![(screenshot)](https://cloud.githubusercontent.com/assets/1088720/13730491/eee3b4dc-e961-11e5-93bc-ea6a82800248.png)

It's not a big deal to have to delete such entries from the tables of contents manually. But it still looks like some bug and thus I decided to have it reported here.

**Comment by Nandaka** [comment]
Assuming this is the redlink=1 pages, I think I can add check when doing update check.

**Comment by Mithgol** [comment]
Yes, these hyperlinks were added to the contents by [an edit](http://www.baka-tsuki.org/project/?diff=prev&oldid=480551) that makes them quite likely to be `redlink=1` initially.

**Comment by Mithgol** [comment]
It works! Thanks.
