### ISSUE TITLE
Links in a few novels dont work

### ISSUE THREAD

**Issue by ecchibunny** [calvinaquino/LNReader-Android#228]
So as the title said. I ran into a few novels that are fully translated on the page and i read them before on the app but now they are empty and tye links dont work. For example Oda Nobuna no Yabou.

**Comment by Nandaka** [comment]
> Oda Nobuna no Yabou.

https://www.baka-tsuki.org/project/index.php?title=Oda_Nobuna_no_Yabou#The_.27Oda_Nobuna_no_Yabou.27_series_by_Kasuga_Mikage
If you check the pages, a lot of chapter is deleted/redlink.

Tested with 1.1.39-beta2

**Comment by ecchibunny** [comment]
Any reason as to why?  I cant find any on the page.  Im sorry about my mistake.

**Comment by Nandaka** [comment]
I don't know, you need to ask to the translator. I'm just getting the data from the baka-tsuki wiki page.
