### ISSUE TITLE
Android app.

### ISSUE THREAD

**Issue by joyys** [calvinaquino/LNReader-Android#229]
I try to look for this issue I'm having but I couldn't find it so I thought I'll post it.
I got the app so I can read on the go but when I'm on the app nothing shows up. I search for a novel but nothing shows up and in any language I might add. I go to the website and the novels I search for on the app appear on desktop but in the app nothing shows up. So I don't know what I need to do to be able to read on the go or be able to see them. 
I have used the app before like 2 months ago and everything work fine but now that I recently install the app again after swapping phones, and now I'm having this issue. Please help. My phone is a note 5 running android 5.1.1
Thank you.

**Comment by Nandaka** [comment]
have you tried to refresh the novel list in the main page?

**Comment by joyys** [comment]
Yea I have. I have even uninstalled it a couple of times from the play store and reinstalled it but I'm experience the same thing. I have tried it with just getting the apk but I'm also experience the same issue. So I don't know. At the end I just quit trying to figure it out.

**Comment by Nandaka** [comment]
but if you try on different device, it is working? if yes, then something in your note5 blocking the access to baka-tsuki webpage.

**Comment by joyys** [comment]
Sorry for late response. I actually had my friend install it on his phone & it didn't work there either. He has an LG phone. So then I tried it on my Sister phone & it work fine. I check the setting to see if they're set the same as my phone and they're, so I don't know what's blocking it like you said... Do you have any idea what my block it?

**Comment by Nandaka** [comment]
what is the android version for your phone, your friend phone, and your sister phone?

Can you open the website from your phone browser?

Is it possible to get the adb log file from your phone, refer to : http://forum.xda-developers.com/showthread.php?t=1726238

**Comment by joyys** [comment]
I actually made to work now. I completely reset my phone. It was a pain because of losing everything but the app works now. I guess there waswas something blocking it so I just reset it. I see the light novels now & such. The search tap works so so far now it looks all good. I can favorite them. Awesome. 
Thank you for replying back.

**Comment by Nandaka** [comment]
:smile:
