### ISSUE TITLE
Another Border Problem

### ISSUE THREAD

**Issue by ghost** [calvinaquino/LNReader-Android#230]
"Contents" in chapter

![screenshot_2016-03-20-19-31-05_com erakk lnreader](https://cloud.githubusercontent.com/assets/17326488/13904229/53d72136-eed4-11e5-884a-2a56b1c6420f.png)

Border in Illustrations page

![screenshot_2016-03-20-19-27-43_com erakk lnreader](https://cloud.githubusercontent.com/assets/17326488/13904231/5ad51470-eed4-11e5-812c-2b13a69f8b6a.png)

It seems that Contents' style inherited from attempt to fix my previous report.

And the image's border in Illustrations page caused border not align (added more pixels). 

Can you fix that? Ignore `#toc #toctitle, .toc #toctitle, #toc .toctitle, .toc .toctitle` or `li.gallerybox div.thumb img` or something?

And sorry for not edit that image.

**Comment by Nandaka** [comment]
the old behaviour will fix the color to rgb 555, is it ok?

https://github.com/calvinaquino/LNReader-Android/commit/736db8f229ffed77771c49fc7264523333dd0eda#diff-0bdc18c1fdf329a379e0961d161b6f6aL199
