### ISSUE TITLE
Image Loading Issue

### ISSUE THREAD

**Issue by Phanotak** [calvinaquino/LNReader-Android#231]
Ok. I'm gonna describe what I did below.
I moved the entire images folder from internal storage to a folder called BT in my external_SD.
Went to settings, storage, images, changed image save location to /storage/external_SD/BT/images.
Tried to relink images, but it always gets stuck on 0 image(s) updated. 
When I go to a novel, the big image isn't there, and a little popup says Bitmap empty. 
When I go to novel illustrations, I can see the list of images, but when I click on one, it just loads the 
broken image thing.
I COULD just move the images folder back to where it was, but it takes up like 800mb of internal storage, which is a lot since my phone only has a 3-4 GB of internal storage.

**Comment by Nandaka** [comment]
Move the image and refresh your page?

Also, what is your device and android version? Google restrict the external sd card access on KitKat and above. 

I think you need to change the path to something like ```/storage/external_SD/Android/data/com.erakk.lnreader/images``` to allow the application to read the sd card.
