### ISSUE TITLE
Every Chapter in every LN is gone

### ISSUE THREAD

**Issue by Cenxiol** [calvinaquino/LNReader-Android#232]
Can't read anything, every novel is either full of Red\Pink chapters or some leads to a different site.
Plus no cover photo just a synopsis.

It was fine yesterday. After I updated a Novel it lost the cover photo and I can't load a single illustration. So I tried clearing the app cache and even clearing my DB. And tried reinstalling the app but its still the same, what's worse I checked to see if its just that single novel but no, everything was gone.

**Comment by Nandaka** [comment]
which novel? ensure the original novel is not deleted from baka tsuki page due to licensing.

**Comment by Cenxiol** [comment]
Everything. Every single Novel from the list not just one. :( I did refresh the list.
That was the first thing that came to mind too, but its not gone from baka tsuki yet.
Tried using a different device but same result.

**Comment by Nandaka** [comment]
Looking the website, looks like they have maintenance from 20-22 May. Can you refresh the novel list again?

I think it got some changes in the background causing the break. I'll look into it.

**Comment by Nandaka** [comment]
OK, found out the root cause:
- BakaTsuki now enforce https, so you need to enable it from Settings -> Update and Notification -> Network -> Use HTTPS  to True.
If it still failed, try to enable Load App Keystore to load the saved certificate.

I'll update the code to ensure the https always set to true.

**Comment by Nandaka** [comment]
**** too soon

**Comment by Nandaka** [comment]
released to google play, or you can get the apk from the releases page: https://github.com/calvinaquino/LNReader-Android/releases

**Comment by Cenxiol** [comment]
Nice! I can see chapters now. Thank you very much! ^-^
But... there is still one more problem (Sorry for being a pain T-T)
It always says bitmap empty (so it won't load a single Cover and illustration) and when I go to read a chapter with a picture it always says:

class javax.net.ssl.SSLHandshakeException:
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

I did enable the Load App Keystore function and the HTTPS one.

**Comment by Nandaka** [comment]
have you try to disable the load app keystore first? Only enable if it is not working.

**Comment by Cenxiol** [comment]
Oh yeah, your right, I just needed to disable it. Its okay now. (Ashamed T-T)
It still always says bitmap empty on every novel though... So there's not a single Cover Photo on the list. 
Anyway! I can read again! Yay! Thank you!

**Comment by Nandaka** [comment]
If you refresh the chapter list, it should try to get cover again. Of course, it is depends on the novel structure in baka-tsuki. At least I can get the cover for Masou Gakuen HxH

**Comment by DangoFan** [comment]
Hi. I was the one who posted #233 I followed the steps above and failed to update my reader

The error says

Error whe getting Novels list: SSL handshake aborted: ssl=0x254f88: Failure in SSl library, usually a protocol error error:14077410:SSL routines: SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:658 0xad127441:0x00000000).

**Comment by Zeushellsing** [comment]
I have exactly the same problem too. except the solution given didnt help at all. 

Displaying the same error each time i tried to read a chapter.

Error Code:
class javax.net.ssl.SSLHandshakeException:
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by Nandaka** [comment]
Have you disable the load app keystore in the setting first?

If this happens, look like your device os root certificate is not updated. 

The current app keystore still pointing to the old server. The new server is using cloudfare. If your device is updated, it should not have any problem with cloudfare https as long you disable the app key store in the settings.

**Comment by Zeushellsing** [comment]
If you are referring to my issue. Exact problem as Cenxiol. Followed the same solution given. Still same problem.

**Comment by Nandaka** [comment]
what is your device? Looks like you don't have cloudflare https certificate. I assume you are using the latest version of bakareaderex (1.1.40)

**Comment by Zeushellsing** [comment]
Currently using Motorola moto x style. Android version 6.0 . bakareaderex is the latest version

**Comment by DangoFan** [comment]
My phone is Samsung Galaxy Mini S5570. Android 4.4 Kitkat. My reader is version 1.1.40

**Comment by Nandaka** [comment]
Try new version 1.1.41 and enable use app key store.

**Comment by Nandaka** [comment]
Also if the cover image is missing, try to enable Hi-Res Cover in Settings -> General -> UI -> Use Hi-Res cover.

**Comment by Zeushellsing** [comment]
Hey it works! Thanks for your help!!

**Comment by revax2** [comment]
Thank it's fixed now

**Comment by DangoFan** [comment]
I'm still getting the same error :(

**Comment by Nandaka** [comment]
Try to turn on/off the Use App Keystore in Settings -> Update and Notification -> Network.

Ensure you can open the site from your device without error.

**Comment by DangoFan** [comment]
Ohh. I cannot open the site from my phone

**Comment by Nandaka** [comment]
Looks like you are using quite old devices which doesn't support the new https encryption. This one I cannot help, as the https is governed by baka-tsuki website.

**Comment by DangoFan** [comment]
Yeah. My phone is quite old. I should upgrade my phone. Thanks :)
