### ISSUE TITLE
Can't download some volumes

### ISSUE THREAD

**Issue by uratex** [calvinaquino/LNReader-Android#235]
Volumes 7.5 & 8.5 of rokujouma are having http error when i try to download them. I already have the app keystore enabled.

**Comment by uratex** [comment]
And also volume 6.5 of ore no kanojo to osananajimi. Maybe all volumes with .5 have a problem since i could download the main volumes just fine.

**Comment by Nandaka** [comment]
yep, the api return 404 not found

https://baka-tsuki.org/api.php?action=parse&format=xml&prop=text|images&redirects=yes&page=Rokujouma_no_Shinryakusha!%3F:_Volume_7.5_Illustrations&*

**Comment by Nandaka** [comment]
somehow the server redirect wrongly (w/o /project/ subdir)

**Comment by Nandaka** [comment]
I think the config is fixed already
