### ISSUE TITLE
the images that i already downloaded is gone or something

### ISSUE THREAD

**Issue by mizzu321** [calvinaquino/LNReader-Android#236]
I don't know when it happen,but the images that i already download like rokujouma,magika kenshi,etc. When i tried to open it, it downloading again though it always fail when i tried to redownload again. And when i click the refresh chapter link for some reason it always fail, it say http error fetching url. Ah and when i tried to download the image it always say wrong keystore, even though i already enable keystore on setting, please help and thanks.

**Comment by Nandaka** [comment]
can you open the webpage in your device/phone?

**Comment by mizzu321** [comment]
That the first thing i tried because i thought the website is down, but in fact i can open it and see the illustration on website

**Comment by Nandaka** [comment]
try to disable the keystore?

**Comment by mizzu321** [comment]
I already tried that too, well i can download the image but still have http issue and the homepage cover is blank too

**Comment by Nandaka** [comment]
Try to enable Use Hi-Res cover in Settings->General? Also give me the details for the http error.

**Comment by mizzu321** [comment]
When i tried to refresh the novel to check the update, at the end it will be retry and said http error fetching url

**Comment by Nandaka** [comment]
can you give the novel and chapter name?

**Comment by mizzu321** [comment]
Baka to test vol 12.5, vol 4 and vo 7 well it's the illustration, also rokujouma and masou gakuen. Sorry have to put out my complain btw.

**Comment by Nandaka** [comment]
the bakatest 12.5 is because of site configuration (somehow it redirect wrongly).

Is the rokujouma also for 7.5? Masou didn't have chapter with . in it, so weird cos I can download in my device.

You can see the illustration in the website from your phone right? Is this the only affected chapters?

**Comment by mizzu321** [comment]
Sorry about masou actually it's already work when i checked it, well fo the final question is about the novel that illustration already i downloaded, can i make it back or have to redownload it? Because when i checked it i still already have the data in my sd card but for some reason it downloading again, well if i have to seems like i will though it will be a little hassle

**Comment by Nandaka** [comment]
assuming it have the same filename and filesize, it won't redownload the file again.

**Comment by mizzu321** [comment]
The problem is it do, that why i confuse.

**Comment by Nandaka** [comment]
It will show up in the message, but it will not download (unless it show the download progress indicator, e.g. 21 of 300kb or something like that).
