### ISSUE TITLE
Can't download main db

### ISSUE THREAD

**Issue by KneeSoxx** [calvinaquino/LNReader-Android#237]
Tried everything, ticking 'use keystore' options then try redownloading db many times, reinstalled app. Still getting error 'HTTP error fetching URL'. Am currently running the latest version of BakaReader  using android 4.4.

**Comment by Nandaka** [comment]
Can you open the website from your phone?

**Comment by KneeSoxx** [comment]
Yes. Even tried clearing partition cache to see if that will change anything but still didn't work.

**Comment by Nandaka** [comment]
are you using any antivirus/firewall? can you give me the adb log file?

**Comment by KneeSoxx** [comment]
[log.txt](https://github.com/calvinaquino/LNReader-Android/files/286317/log.txt)
is this good enough? btw im not using any antivirus/firewall of any sort on my phone and no firewalls on network either.

**Comment by KneeSoxx** [comment]
Also, I'd like to add that what I'm getting is an HTTP error one and not HTTPS (not sure if those are different errors) and if they're different is why does it occur if you've already set it to be always HTTPS.

**Comment by BoreDom9595** [comment]
I hope you can find an solution , cause i have the same problem

**Comment by Nandaka** [comment]
your log doesn't show the required part. please filter by appname = com.erakk.lnreader and try to perform the novel list refresh when logging. refer to http://stackoverflow.com/a/6854182

If you able to browse in the phone browser, ensure the use app keystore is turned off.

about http error, that one is hardcoded in the message I think.

@BoreDom9595 : Do you able to browse the bakatsuki website from browser phone? what is your device and android version?

**Comment by BoreDom9595** [comment]
Yeah i can Browse the Website , and androidversion is 4.4 already tried a few things i read online but none oft it helped

**Comment by Nandaka** [comment]
This is due to the Admin change the site config, will update.

**Comment by Nandaka** [comment]
try https://github.com/calvinaquino/LNReader-Android/releases/tag/1.1.42

**Comment by BoreDom9595** [comment]
Thank you , works great ,👍

**Comment by KneeSoxx** [comment]
Latest release also worked. Thanks mate :D
