### ISSUE TITLE
Some Illustrations are blank

### ISSUE THREAD

**Issue by BrokenRevenue** [calvinaquino/LNReader-Android#238]
After downloading novels some of the illustrations go blank.

**Comment by BrokenRevenue** [comment]
even the novel cover goes blank

**Comment by Nandaka** [comment]
give me more details.

Also try to enable use Hi-Res cover in Settings -> General.

**Comment by BrokenRevenue** [comment]
after downloading ore no kanojo the illustrations on volume 3 and 4 went missing. And when i refresh novels, the novel cover goes blank saying bitmap empty. And when i turn on the Hi res on settings, it got stuck on fetching details.

**Comment by BrokenRevenue** [comment]
the novel cover seems downloaded after using the hi res in settings thanks but i cant recover the novel illustrations of ore no kanojo vol. 3 and 4

**Comment by Nandaka** [comment]
delete the chapter and refresh?

**Comment by Trollhand** [comment]
Experiencing the cover images problem, too. The problem seems to be with the outdated image link. Deleting the novel didn't resolve the issue.

![screenshot_2016-05-28-22-19-46](https://cloud.githubusercontent.com/assets/19627073/15629532/7f113c80-2523-11e6-9edf-ed36bfdd0378.png)

**Comment by BrokenRevenue** [comment]
oh another problem pops up. I cant refresh my novels. every time i refresh it will say https fetching url error. but i can download novels. creepy.

**Comment by Nandaka** [comment]
For the cover issue, I think I found the issue. Most likely due to http to
https redirect. Will fix

**Comment by Nandaka** [comment]
Try https://github.com/calvinaquino/LNReader-Android/releases/tag/1.1.43
