### ISSUE TITLE
Https fetching url error

### ISSUE THREAD

**Issue by BrokenRevenue** [calvinaquino/LNReader-Android#239]
Every time i refresh my novels it always says https fetching url error. I already updated the app nut its no use. I can't refresh my novels but i can download other novels. creepy.

**Comment by Nandaka** [comment]
can you open the bakatsuki website from the phone browser?
Have you tried to enable/disable Use App Keystore from Settings -> Update & notification?

please give me more information.

**Comment by kingandy44** [comment]
I having the same problem with the main and updates

**Comment by kingandy44** [comment]
I can't open up the bakatsuki website on my phone browser

**Comment by kingandy44** [comment]
I tried to uninstalling it and then reinstalling it but it still doesn't work

**Comment by Nandaka** [comment]
If you cannot open the site in your phone browser, looks like you need to upgrade your android phone.

The new site now forces HTTPS with new encryption method which not supported in old phone.

I cannot do anything about this.
