### ISSUE TITLE
Chapter fetching error

### ISSUE THREAD

**Issue by wiseliu** [calvinaquino/LNReader-Android#240]
BakaReaderEX error, the epilogue, afterword, and bonus chapter for The Zashiki Warashi of Intellectual Village cannot be downloaded in the app, but the chapter 4 is updated normally. the URL for failed download are
https://baka-tsuki.org/project/index.php…
https://baka-tsuki.org/project/index.php…
https://baka-tsuki.org/project/index.php…
https://baka-tsuki.org/project/index.php…
the logcat are in this URL : https://dl2.pushbulletusercontent.com/6Ty3VKJEH8…/logcat.txt

**Comment by wiseliu** [comment]
the browser can open baka tsuki web normally, the app keystore options are turned off

**Comment by Nandaka** [comment]
the urls are cut off.

**Comment by wiseliu** [comment]
Huh? Do you have any idea to fix the problem? Im using android ICS 4.0.4

**Comment by wiseliu** [comment]
On Jun 1, 2016 5:23 PM, "Nandaka" <notifications@github.com> wrote:

> the urls are cut off.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/calvinaquino/LNReader-Android/issues/240#issuecomment-222953032>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARy9a6xLmks5-O8wyT4PpF4lFfp0gVtvks5qHV25gaJpZM4IrMPw>
> .
>

06-01 11:41:47.443 D/libc-netbsd(31132): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:41:47.474 D/libc-netbsd(95): res_queryN name = baka-tsuki.org, class = 1, type = 1
06-01 11:41:47.512 D/libc-netbsd(95): res_queryN name = baka-tsuki.org succeed
06-01 11:41:47.518 D/libc-netbsd(31132): getaddrinfo: baka-tsuki.org get result from proxy >>
06-01 11:42:03.271 D/libc-netbsd(31132): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:42:09.788 D/libc-netbsd(31132): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:42:23.183 D/libc-netbsd(31132): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:42:28.494 D/libc-netbsd(31132): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:42:30.724 E/class com.erakk.lnreader.task.LoadNovelDetailsTask(31132): org.jsoup.HttpStatusException: HTTP error fetching URL. Status=414, URL=https://baka-tsuki.org/project/api.php?action=query&prop=info|revisions|categories&cllimit=max&format=xml&redirects=yes&titles=|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Illustrations|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Prologue|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Chapter_1|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Chapter_2|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Chapter_3|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Chapter_4|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Afterword|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Illustrations|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Chapter_1|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Chapter_2|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Chapter_3|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Chapter_4|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Afterword|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume3_Illustrations|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume3_Prologue|The_Zashiki_Warashi_of_Intellectual_Village:Volume3_Chapter_%3F|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume3_Afterword|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume3_Epilogue|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Illustrations|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Chapter_1|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Chapter_2|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Chapter_3|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Chapter_4|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Epilogue|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Afterword|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume5_Illustrations|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume5_Side_A|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume5_Notice|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume5_Side_B|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume5_Package_Console_System
06-01 11:42:30.736 E/class com.erakk.lnreader.UI.fragment.DisplayLightNovelDetailsFra(31132): org.jsoup.HttpStatusException: HTTP error fetching URL. Status=414, URL=https://baka-tsuki.org/project/api.php?action=query&prop=info|revisions|categories&cllimit=max&format=xml&redirects=yes&titles=|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Illustrations|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Prologue|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Chapter_1|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Chapter_2|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Chapter_3|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Chapter_4|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Afterword|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Illustrations|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Chapter_1|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Chapter_2|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Chapter_3|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Chapter_4|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Afterword|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume3_Illustrations|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume3_Prologue|The_Zashiki_Warashi_of_Intellectual_Village:Volume3_Chapter_%3F|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume3_Afterword|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume3_Epilogue|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Illustrations|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Chapter_1|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Chapter_2|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Chapter_3|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Chapter_4|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Epilogue|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Afterword|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume5_Illustrations|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume5_Side_A|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume5_Notice|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume5_Side_B|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume5_Package_Console_System
06-01 11:42:32.929 D/libc-netbsd(31132): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:42:38.229 D/libc-netbsd(31132): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:42:56.599 D/libc-netbsd(31132): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:43:02.441 D/libc-netbsd(31132): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:43:07.330 E/class com.erakk.lnreader.task.LoadNovelDetailsTask(31132): org.jsoup.HttpStatusException: HTTP error fetching URL. Status=414, URL=https://baka-tsuki.org/project/api.php?action=query&prop=info|revisions|categories&cllimit=max&format=xml&redirects=yes&titles=|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Illustrations|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Prologue|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Chapter_1|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Chapter_2|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Chapter_3|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Chapter_4|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Afterword|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Illustrations|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Chapter_1|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Chapter_2|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Chapter_3|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Chapter_4|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Afterword|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume3_Illustrations|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume3_Prologue|The_Zashiki_Warashi_of_Intellectual_Village:Volume3_Chapter_%3F|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume3_Afterword|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume3_Epilogue|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Illustrations|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Chapter_1|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Chapter_2|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Chapter_3|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Chapter_4|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Epilogue|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Afterword|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume5_Illustrations|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume5_Side_A|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume5_Notice|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume5_Side_B|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume5_Package_Console_System
06-01 11:43:07.361 E/class com.erakk.lnreader.UI.fragment.DisplayLightNovelDetailsFra(31132): org.jsoup.HttpStatusException: HTTP error fetching URL. Status=414, URL=https://baka-tsuki.org/project/api.php?action=query&prop=info|revisions|categories&cllimit=max&format=xml&redirects=yes&titles=|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Illustrations|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Prologue|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Chapter_1|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Chapter_2|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Chapter_3|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Chapter_4|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume1_Afterword|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Illustrations|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Chapter_1|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Chapter_2|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Chapter_3|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Chapter_4|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume2_Afterword|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume3_Illustrations|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume3_Prologue|The_Zashiki_Warashi_of_Intellectual_Village:Volume3_Chapter_%3F|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume3_Afterword|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume3_Epilogue|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Illustrations|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Chapter_1|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Chapter_2|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Chapter_3|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Chapter_4|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Epilogue|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume4_Afterword|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume5_Illustrations|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume5_Side_A|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume5_Notice|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume5_Side_B|The_Zashiki_Warashi_of_Intellectual_Village%3AVolume5_Package_Console_System
06-01 11:47:51.602 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:47:51.606 D/libc-netbsd(95): res_queryN name = baka-tsuki.org, class = 1, type = 1
06-01 11:47:52.038 D/libc-netbsd(95): res_queryN name = baka-tsuki.org succeed
06-01 11:47:52.044 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org get result from proxy >>
06-01 11:48:05.083 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:48:08.157 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:48:22.468 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:48:25.325 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:48:27.233 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:48:28.366 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:48:36.830 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:48:59.978 D/libc-netbsd(3645): getaddrinfo: www.baka-tsuki.org  return error = 0x8 >>
06-01 11:48:59.979 D/libc-netbsd(95): res_queryN name = www.baka-tsuki.org, class = 1, type = 1
06-01 11:49:00.026 D/libc-netbsd(95): res_queryN name = www.baka-tsuki.org succeed
06-01 11:49:00.027 D/libc-netbsd(3645): getaddrinfo: www.baka-tsuki.org get result from proxy >>
06-01 11:49:00.756 D/libc-netbsd(3645): getaddrinfo: www.baka-tsuki.org  return error = 0x8 >>
06-01 11:49:19.095 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:49:22.853 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:49:28.494 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:49:34.799 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:49:38.010 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:49:40.844 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:49:44.479 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:49:59.223 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:50:06.258 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:50:10.471 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:50:18.724 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:50:23.752 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:50:26.151 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:50:33.285 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:50:38.010 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:50:43.404 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:50:47.827 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:50:49.765 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:50:52.654 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:50:57.133 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:51:20.815 D/libc-netbsd(3645): getaddrinfo: www.baka-tsuki.org  return error = 0x8 >>
06-01 11:51:21.343 D/libc-netbsd(3645): getaddrinfo: www.baka-tsuki.org  return error = 0x8 >>
06-01 11:52:44.979 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:52:48.737 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:52:51.679 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:52:56.639 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:53:03.244 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:53:08.277 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:53:10.730 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:53:14.845 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:53:17.322 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:53:19.367 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:53:23.479 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:53:25.927 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:53:28.496 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:53:32.323 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:53:37.871 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:54:29.236 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:54:38.266 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:54:40.797 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:54:46.177 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:54:49.664 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:54:55.717 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:55:11.637 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:55:15.670 E/class com.erakk.lnreader.parser.BakaTsukiParser(3645): Chapter is missing/deleted: //baka-tsuki.orgThe_Zashiki_Warashi_of_Intellectual_Village:Volume9_Illustrations
06-01 11:55:15.681 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:55:21.970 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:55:23.996 E/class com.erakk.lnreader.parser.BakaTsukiParser(3645): Chapter is missing/deleted: //baka-tsuki.orgThe_Zashiki_Warashi_of_Intellectual_Village:Volume9_Prologue
06-01 11:55:24.027 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:55:26.879 E/class com.erakk.lnreader.parser.BakaTsukiParser(3645): Chapter is missing/deleted: //baka-tsuki.orgThe_Zashiki_Warashi_of_Intellectual_Village:Volume9_Chapter_1
06-01 11:55:26.928 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:55:30.153 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:55:34.269 E/class com.erakk.lnreader.parser.BakaTsukiParser(3645): Chapter is missing/deleted: //baka-tsuki.orgThe_Zashiki_Warashi_of_Intellectual_Village:Volume9_Chapter_2
06-01 11:55:35.874 E/class com.erakk.lnreader.parser.BakaTsukiParser(3645): Chapter is missing/deleted: //baka-tsuki.orgThe_Zashiki_Warashi_of_Intellectual_Village:Volume9_Chapter_3
06-01 11:55:35.931 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:55:39.254 D/libc-netbsd(3645): getaddrinfo: baka-tsuki.org  return error = 0x8 >>
06-01 11:55:40.777 E/class com.erakk.lnreader.parser.BakaTsukiParser(3645): Chapter is missing/deleted: //baka-tsuki.orgThe_Zashiki_Warashi_of_Intellectual_Village:Volume9_Chapter_4
06-01 11:55:41.726 D/class com.erakk.lnreader.UI.fragment.DisplayLightNovelDetailsFra(3645): Page: //baka-tsuki.orgThe_Zashiki_Warashi_of_Intellectual_Village:Volume9_Illustrations
06-01 11:55:41.726 D/class com.erakk.lnreader.UI.fragment.DisplayLightNovelDetailsFra(3645): Page: //baka-tsuki.orgThe_Zashiki_Warashi_of_Intellectual_Village:Volume9_Prologue
06-01 11:55:41.726 D/class com.erakk.lnreader.UI.fragment.DisplayLightNovelDetailsFra(3645): Page: //baka-tsuki.orgThe_Zashiki_Warashi_of_Intellectual_Village:Volume9_Chapter_1
06-01 11:55:41.726 D/class com.erakk.lnreader.UI.fragment.DisplayLightNovelDetailsFra(3645): Page: //baka-tsuki.orgThe_Zashiki_Warashi_of_Intellectual_Village:Volume9_Chapter_2
06-01 11:55:41.726 D/class com.erakk.lnreader.UI.fragment.DisplayLightNovelDetailsFra(3645): Page: //baka-tsuki.orgThe_Zashiki_Warashi_of_Intellectual_Village:Volume9_Chapter_3
06-01 11:55:41.726 D/class com.erakk.lnreader.UI.fragment.DisplayLightNovelDetailsFra(3645): Page: //baka-tsuki.orgThe_Zashiki_Warashi_of_Intellectual_Village:Volume9_Chapter_4

**Comment by wiseliu** [comment]
Already sent the logcat, hope you received it

**Comment by Nandaka** [comment]
wut, are you running v1.1.42?
https://github.com/calvinaquino/LNReader-Android/releases/tag/1.1.42

**Comment by wiseliu** [comment]
Yeah

**Comment by Nandaka** [comment]
try https://github.com/calvinaquino/LNReader-Android/releases/tag/1.1.43

**Comment by wiseliu** [comment]
ver 1.1.43 fixed the problem, however i dont have any chance to test on another novel and title. should i leave this issue open until i verified its working for all novel?

**Comment by wiseliu** [comment]
the bonus chapter on zashiki warashi only updated to part 3 (https://baka-tsuki.org/project/index.php?title=The_Zashiki_Warashi_of_Intellectual_Village:Bonus_Part_3), immediately after i see it on novelupdates. boh my phone are running 1.1.43, and the OS for both phone are 6.0.1 marshmallow and 4.0.1 ics.

**Comment by BrokenRevenue** [comment]
Ecountering the problem again. Latest app version. URL fetching error
