### ISSUE TITLE
Missing Chapters for Volumes after server migration.

### ISSUE THREAD

**Issue by Wolfpup67** [calvinaquino/LNReader-Android#241]
The app is not getting new chapters for some Series after BakaTsuki moved to a new server.
Series with missing chapters found so far:
Masou Gakuen HxH :  Vol 5(Prologue - afterword), Vol 6(Prologue - 
HighSchool DxD : HighSchool DxD  EX(Illustrations - current chapter)

These are the ones I have seen so far.
 and I'm on the current version of the app

**Comment by Nandaka** [comment]
Try to refresh manually? It is works in my phone/emulator and it is loaded.

Also remember to star the novel and enable auto update in the settings.

**Comment by Wolfpup67** [comment]
I have tired all those plus clearing the DB file and reloading it. After the update to the new version Masou Gakuen HxH is ok now but HighSchool DxD is sill missing a volume. my tablet and phone are both running Android 4.4.4 and i can see the chapters fine using the browser in them.

**Comment by Nandaka** [comment]
I suspect this is because the Aggresive Book Title Clean Up is enabled in Settings -> Updates and Notification.

**Comment by Wolfpup67** [comment]
I tried turning that off and refreshing the novel list for HighSchool DxD but all that did was add (Full Text) to the end of each volume that was already listed it did not add the missing volume.

**Comment by Nandaka** [comment]
> Highschool DxD EX

This is because the keyword (Bluray Specials) is not included in the list
https://github.com/calvinaquino/LNReader-Android/blob/master/app/src/main/java/com/erakk/lnreader/parser/BakaTsukiParser.java#L197

The easiest way is by changing the h2 id text from 'Blu-Ray_Specials' to 'Blu-Ray_Specials_by_Ichiei_Ishibumi'
