### ISSUE TITLE
[BUG] Images aren't loading from storage

### ISSUE THREAD

**Issue by ShadowfoxEX** [calvinaquino/LNReader-Android#242]
I dont know if you've read my forum post or not, but altogether, none of the images are loading anymore. Neither from a new connection nor from my phone storage

**Comment by Nandaka** [comment]
since when? Ensure Settings -> Reading Layout -> Show Images is enabled. Also check if you can open the page in your phone browser.

I'm using 1.1.43 and it is loaded properly (checked w/ Masou Gakuen) even after refresh.

**Comment by ShadowfoxEX** [comment]
Since last patch. The details again that absolutely none of the images are loading for me anymore, Online nor offline, Especially offline because it keeps trying to connect to the internet instead of loading it from the web. When it does try to load online, when I go to the image link, it goes "Fetching" then "Downloading", "Retry:0x...1x...2x", and then the images fail to load. 

I don't know if it's the update, but I'm going to reinstall it

**Comment by Nandaka** [comment]
possible to get the adb log file? 
Usually it will try to connect to the internet if the application cannot find the image in the local storage.
Also, looks like something preventing it to access the internet? check the application permission? Also try to enable/disable the app key store?

**Comment by ShadowfoxEX** [comment]
Hold on, I reinstalled and it's working, but trying to restore everything from a database. I think my phone updated to 6.0 at the same time you updated it to 1.1.43, and from experience with google and updates, they do NOT like external SD cards, where I've been storing all my images

**Comment by ShadowfoxEX** [comment]
Sure enough, old settings where I had the app on the phone and linked the image storage to the phone it caused all the images to break. Found the fix on google forums, I have to transfer the app data to the SD card, so images are somewhat loading, I'm going to try and repair the database to check one or two more things because images aren't loading on the novels that are no longer hosted on baka tsuki

**Comment by ShadowfoxEX** [comment]
Okay, now it's all working, peachy. Google does not like giving free access to apps for the SD card. Not your fault, it was google's, and my insatiable 128 GB of storage.

**Comment by Nandaka** [comment]
can you provide the link of the fix? I can use it as reference when I'm upgrading to android 6.0

**Comment by ShadowfoxEX** [comment]
It's an SD card problem with google, since 4.0 they've blocked external SD file editing with the exception of images. Music files were the same unless the app developer or phone manufacturer allowed it, dont know the details on that, but since 5.0 they allowed a setup where you can transfer all the app data from your phone storage to your SD card, simply going to settings>device>apps>[APP]>Storage. I did this with my music in 5.0 and now they've blocked images in 6.0.

**Comment by Nandaka** [comment]
hmm, what about using ```/storage/sdcard1/Android/data/<package_name>``` or some variation of it?

**Comment by ShadowfoxEX** [comment]
Doesnt work, permissions are strange
