### ISSUE TITLE
When app is started reading location is lost and web novels do not appear in the watch novel section

### ISSUE THREAD

**Issue by tquon** [calvinaquino/LNReader-Android#244]
Hi, I have found two issues.

First issue is when the app is just launched and you are returning to a chapter you have started reading, either from the "Resume novel" button or manually the reading location is pushed to the bottom.

The second issue is a minor one which is watched novels in the web tab do not appear in the Watch novel list.

I am using a Asus Zenfone 2 with Android 6.0.1. My baka reader version is 1.1.43.

Thank you for your work. Really enjoy the app.

**Comment by Nandaka** [comment]
I'm not quite clear on the 1st issue? Can you show me the step by step details?

2nd issue: will fix.

**Comment by tquon** [comment]
I have tried testing the issue again but I can't seem to reproduce the issue.

The steps I took were.
1. Launch app
2. Select any novel chapter
3. Move the page a bit
4. Open running app page (My Zenfone has a dedicated button to it)
5. Close Baka-Tsuki 
6. Launch app
7. Open to previous chapter with "Resume Novel" or manually

At the time this issue was happening every time but now it doesn't. I am still using the same android and app version. Let me know if you need more details.

**Comment by Nandaka** [comment]
Assuming the close button does not kill the process (e.g. similar like Window Task Manager's End Process), then it should not happen.

the last location is saved during activity OnFinish() cycle.
