### ISSUE TITLE
Font default reset button suggestion

### ISSUE THREAD

**Issue by tquon** [calvinaquino/LNReader-Android#245]
Hi, 

I would like to submit a suggestion for the app.

Could you add a reset font button within the 3 dot menu dropdown?

I really like the default font size but sometimes returning to old chapters after the app updates will have the font smaller. Having the button would be helpful.

Thank you for the app.

**Comment by Nandaka** [comment]
You can do global reset of zoom level from Settings -> Reading Layout -> Reset Zoom Level
