### ISSUE TITLE
unable to properly read World Teacher chapter

### ISSUE THREAD

**Issue by kotoroshinoto** [calvinaquino/LNReader-Android#246]
Volume 2 Chapter 4 won't load within the app. Probably has the wrong web address or something

**Comment by kotoroshinoto** [comment]
if I allow it to open in browser, it opens the link properly, if I tell the app to use the built in web viewer, it flashes the text for a moment and then unloads it showing an error instead.

**Comment by Nandaka** [comment]
I think got some issue related on how android save the wordpress pages as mht  and try to reload it again.

need more checking.
