### ISSUE TITLE
Unable to fetch english novels

### ISSUE THREAD

**Issue by redcloack** [calvinaquino/LNReader-Android#247]
Latly baka reader seems unable to fetch any english language novel (french and polish works) 
Every time it presents the error status=502

**Comment by bakapervert** [comment]
I have got the same issue. I can refresh teaser and web novel. But refreshing main alwaysend in error 502.

By the way can anyone teach me the way to do manual add? I don't know what to fill i  the page box.

**Comment by bakapervert** [comment]
Thanks for the reply. I'll try it out.
