### ISSUE TITLE
Main Light Novels won't download!

### ISSUE THREAD

**Issue by Atamisk89** [calvinaquino/LNReader-Android#248]
The title says it all the main Light Novels section won't download, it says HTTP error when fetching URL.

**Comment by Nandaka** [comment]
what is the error code?

**Comment by Vhin001** [comment]
Same issue with mine. I got a screenshot on it but, don't know how to upload or send it.

**Comment by Vhin001** [comment]
But, I'll type the exact and completr message anyway if that would help.

(When I try to manually refresh as it say)
Message: Error when getting Novel List: HTTP error fetching URL.

(Pop-up message): class org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403

**Comment by Nandaka** [comment]
403 = Access Forbidden.

Are you able to load the webpage https://baka-tsuki.org/project/index.php?title=Main_Page from browser?

**Comment by Mithgol** [comment]
@Vhin001

> I got a screenshot on it but, don't know how to upload or send it.

Save that screenshot in a file on your device, then use the hint “Attach files by dragging & dropping or selecting them” under the comment area of the issue.

See “[Issue attachments](https://github.com/blog/1347-issue-attachments)” for details.

![(animated screenshot)](https://camo.githubusercontent.com/a57126766f5a9f3c76d79dffc6c37dcef2c18dbe/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f32312f3637382f32343861616336612d343061322d313165322d396137362d6664353964656432386262652e676966)
