### ISSUE TITLE
Red Link in hagure no yuusha Aesthetica

### ISSUE THREAD

**Issue by Kuroganex** [calvinaquino/LNReader-Android#249]
Hello i had such many trouble .. Many chapter in some novels had red link and when i open it.. It say empty content ... Please i need help

**Comment by Nandaka** [comment]
Can you open the BakaTsuki website from your phone? 

I can open it in my device (Android 5.1)

**Comment by Kuroganex** [comment]
Umm sorry i mean it was about bakareader app.. I try this app for 3 days and when i check some novels it had many missing chapters like hagure yuusha no aesthetica volume 2 completely missing .. I can open bakatsuki website use my browser.. and i check hagure no yuusha use browser .. And i found volume 2 no text too... Did Hagure Yuusha novels chapt

**Comment by Nandaka** [comment]
Just to clarify with you: so all the available chapters in baka tsuki website can be loaded in the app?

**Comment by Kuroganex** [comment]
And i found volume 2 no text and it was deleted... Did hagure yuusha novels not translated completely ? Because volume 4 in bakareader is avalaiable... And only volume 2 and 3 are missing

**Comment by Nandaka** [comment]
I have no idea, you better check with the translator on bakatsuki forum.

**Comment by Kuroganex** [comment]
Umm yeah i think i not check it properly... The other volume are avalaiable...

**Comment by Kuroganex** [comment]
Okay thanks for the help
