### ISSUE TITLE
novels no longer download

### ISSUE THREAD

**Issue by AltrianHawk** [calvinaquino/LNReader-Android#250]
When I try and download new chapters or anything it just says "wrong key store". This has been happening since the April update.

**Comment by Nandaka** [comment]
Try to disable key store from Settings -> Update & Notification -> Network -> Load App Keystore?

I've tried on both emulator (KitKat) and my phone (Marshmallow) with the option enabled and I see no issue?

Are you using older android version?

**Comment by Mithgol** [comment]
@AltrianHawk Also, do you see any issues opening https://www.baka-tsuki.org/project/index.php?title=Main_Page in a mobile browser on the same device?

**Comment by AltrianHawk** [comment]
Yes I am using an older tablet I suspected that might be the issue.

**Comment by Nandaka** [comment]
Please verify and then close the issue.
