### ISSUE TITLE
Error when getting Novels List

### ISSUE THREAD

**Issue by BakaTenshi** [calvinaquino/LNReader-Android#251]
When I try Refresh Novel List I get this error

> SSL handshake aborted:
ssl=0x27a568: Failure in SSL
library, usually a protocol error
error:14077410:SSL routines:
SSL3_GET_SERVER_HELLO:sslv3
alert handshake failure (external/
openssl/ssl/s23_clnt.c:658
0xad127565:0x00000000)

**Comment by Nandaka** [comment]
Are you using old android version (below 4)? It looks like doesn't support the new Baka Tsuki HTTPS crypto.

**Comment by BakaTenshi** [comment]
Oh ... that will be it. I have 2.3.6. Can I get somewhere older version of app? I remember using it like 1-2 years ago without problem.

**Comment by Nandaka** [comment]
It is on the server side. Baka Tsuki only allow HTTPS since they move the server.
