### ISSUE TITLE
Can't load new novels after reinstalling from 0

### ISSUE THREAD

**Issue by VaesinAdaar** [calvinaquino/LNReader-Android#256]
The app keeps saying trustanchor not validated regardless of how many times I delete the entire thing and redownload from scratch...I cannot access any new novels or chapters on my phone as well as it giving me a bitmap empty error...this started up last week when servers went down, quite annoying.

**Comment by Nandaka** [comment]
They changed the SSL certificate to letsencrypt.org

Try to disable the Load App Keystore in Settings -> Update & Notification.

**Comment by CSGOBETPROFITS** [comment]
Yeah this happened to me too. I factoried resetted twice and disabled the load app keystore but it still says bitmap error and trust anchor java error or something

**Comment by Nandaka** [comment]
can you open the website from your phone browser without issue?

**Comment by lyram21** [comment]
how do i disable the load app keystore??? on which setting??

**Comment by Nandaka** [comment]
Settings -> Update & Notification -> un-tick Load App Keystore.

**Comment by lyram21** [comment]
yeah i saw it sorry for being an idiot
