### ISSUE TITLE
Viewing picture problem

### ISSUE THREAD

**Issue by RealDoodler** [calvinaquino/LNReader-Android#257]
When i tap a picture to show its full size, it said :

class
javax.net.ssl.SSLHandshakeException:
java.security.cert.CertPathValidatorException:
Trust anchor for certification path not found.

**Comment by Nandaka** [comment]
They changed the SSL certificate to letsencrypt.org

Try to disable the Load App Keystore in Settings -> Update & Notification.

**Comment by RealDoodler** [comment]
Edit : now not just the picture, but the new chapter that i haven't read.

**Comment by RealDoodler** [comment]
Oh wait a minute, just restarting the app seems works, thanks a lot
