### ISSUE TITLE
Downloading and then reading offline issue

### ISSUE THREAD

**Issue by curseryu** [calvinaquino/LNReader-Android#258]
On both my tablet and lg g4 both running Android 6.0 i am unable to download completely all chapterset or  volumes of seirei tsukai no blade dance keep getting an error stating class javex.net.ssl.SSL hand exception trust anchor for certification path not found. Not sure I have anything that could block it. I am able to access the baka-tsukis website so I don't think that's the problem. Also get bitmap empty popping up from time to time. Also seems to affect trying to download other light novels other than this one and even after turning off wifi and data it also states that cannot load due to be disconnected from the Internet but I hit download so not sure why that comes up. Any help I can get to resolve this issue would be fantastic as I love the concept of this app and badly want to use this to the fullest extent possible 
![20161015_041432](https://cloud.githubusercontent.com/assets/22854104/19409762/602fc784-9290-11e6-9388-e07d966e6c0e.png)

**Comment by Mithgol** [comment]
Your issue migth be the same as #257.
