### ISSUE TITLE
Bug on novel cover due to thumbnail handling.

### ISSUE THREAD

**Issue by lyram21** [calvinaquino/LNReader-Android#259]
bitmap empty... and the chapter links are all red...

**Comment by Nandaka** [comment]
can you open the site from phone browser?

**Comment by lyram21** [comment]
yes i can open it without any problems

**Comment by belldandu** [comment]
It appears that i have this exact same issue too and i load the site just fine in a browser.
Samsung galaxy note 5 & samsung galaxy tab s2. Both are using Android 6.0.1 firmware

**Comment by belldandu** [comment]
App version 1.1.45

**Comment by belldandu** [comment]
It should be noted that all the chapters say they were last updated 6 years ago. And when you set (download hi res image) instead of getting "bitmap empy" you get a rediculously pixelated image for the cover.

**Comment by belldandu** [comment]
Should also be noted that some projects like this one https://www.baka-tsuki.org/project/index.php?title=Seikoku_no_Ryuu_Kishi are not shown in the main list of the app no matter how much i refresh. Which makes me beleive the app is pulling from an outdated source.

**Comment by belldandu** [comment]
Managed to get above project to show after playing around with settings but chapters still are red

**Comment by belldandu** [comment]
Aha here's a screenshot of an error
![tmp_28859-screenshot_20161031-0056571907915737](https://cloud.githubusercontent.com/assets/5639384/19844631/fcb2a682-9f04-11e6-9500-c6090ee68465.png)

**Comment by belldandu** [comment]
![tmp_28859-screenshot_20161031-005820-2087104504](https://cloud.githubusercontent.com/assets/5639384/19844652/3865b2dc-9f05-11e6-8ab2-1ab1d478a395.png)

**Comment by belldandu** [comment]
Just a heads up i am online.

**Comment by belldandu** [comment]
Ah as it turns out the app is trying to connect and grab from a dead server which is why its failing. They got a new server on october 10th.

**Comment by Nandaka** [comment]
From the screenshot, it shows that the connection is refused.

The ip address shown in the error message supposed to be the new server.

[image: Inline image 1]

[image: Inline image 2]

> cover image = bitmap empty

This one is a bug because of changes on thumbnail handling.Using HiRes
cover in Settings -> General can fix this.

**Comment by lyram21** [comment]
the images are fixed sir ghen how about the chapters?

**Comment by belldandu** [comment]
Is there a reason you guys dont use the mediawikia api instead of scraping the site?

**Comment by Nandaka** [comment]
@belldandu 
I'm using both api and scraping.

API portion to retrieve body content and update info.
Scraping from the api return to parse the novel structure/chapters from the novel detail page (this one I'm not sure how to retrieve the structure using api).

The contents itself is returned by api call.
https://github.com/calvinaquino/LNReader-Android/blob/master/app/src/main/java/com/erakk/lnreader/dao/NovelsDao.java#L1103

https://github.com/calvinaquino/LNReader-Android/tree/master/app/src/main/java/com/erakk/lnreader/parser

**Comment by yuinyaa** [comment]
The image issue is already fixed but all my chapter are still redlink and cannot be seen at all, when I open the page, it shows " The page you specified doesn't exist"

**Comment by Shadowys** [comment]
Just curious why is the IP address used instead of the domain name?

**Comment by yuinyaa** [comment]
@shadowys I am not too well verse in computer program language

**Comment by Shadowys** [comment]
@yuinyaa Actually I was pinging @Nandaka sorry.
