### ISSUE TITLE
Baka tsuki chapter unable to see and download

### ISSUE THREAD

**Issue by yuinyaa** [calvinaquino/LNReader-Android#261]
Every light novel i open the chapter are red in colour and cannot be open nor download, anyways to solve it?

**Comment by Nandaka** [comment]
try to refresh the chapter list.

most likely duplicate with #259

**Comment by Nandaka** [comment]
confirm due to bug in my code. 
baka tsuki now redirect to www.baka-tsuki.org, notice the www.

Will fix
