### ISSUE TITLE
feature request: an option to choose another hostname (a mirror) for Baka-Tsuki

### ISSUE THREAD

**Issue by Mithgol** [calvinaquino/LNReader-Android#262]
An idea of a feature: an option to choose an unofficial mirror of Baka-Tsuki or a non-specific anonymizing “proxy” server (not related to Baka-Tsuki specifically), such as http://h_t_t_p_s.www.baka-tsuki.org.3s3s.org/project/index.php?title=Mahou_Sensou instead of https://www.baka-tsuki.org/project/index.php?title=Mahou_Sensou for example.

Rationale:

* Such an option would work around ceritifcate-related problems in older Android versions because HTTPS-only Baka-Tsuki web site would be accessed through an HTTP-based mirror or “proxy”.

* Such an option would work around govermental censorship in jurisdictions where Baka-Tsuki is under an official ban (because of a court's decision) but a mirror or proxy is not banned (because it would require a separate court's decision).

**Comment by Nandaka** [comment]
will it affect externally hosted novel?

**Comment by Mithgol** [comment]
Some web anonymizers, such as `3s3s.org` in the above example, will rewrite the externally hosted novel's web address to force it to be loaded through the same anonymizer.

It probably won't negatively affect the external novel's reading, but

* anonymizers can affect the perceived date and and time of the remote web page (in HTTP reply headers),

* anonymizers can add their advertisement to the top (or bottom) of the page.

**Comment by Nandaka** [comment]
it might have issue with external novel, as I'm using the hostname to differentiate baka tsuki and other sites.

Also, some sites (wordpress/blogger) will redirect the page from desktop to mobile version.

**Comment by Mithgol** [comment]
I believe that the issue with the hostname-based differentiation can either be ignored or be successfully mitigated for many such proxies.

For instance, the existing hostname difference between `www.baka-tsuki.org` and an external `example.org` would turn to an observable hostname difference between the proxied `h_t_t_p_s.www.baka-tsuki.org.3s3s.org` and an external `example.org.3s3s.org` in the above example.

(You'd just have to use the proxy's hostname instead of original Baka-Tsuki's hostname in your checks.)

As for the last part, related to mobile versions, I admit I am not sure I get it right. Would you elaborate it a bit further?

**Comment by Nandaka** [comment]
For external novel, I don't use the baka tsuki url to store the reference and some blog will return mobile version (e.g. for blogspot, they will append ```?m=1``` to the url automatically, while in the baka tsuki novel page, it only show the normal desktop url)

Refer to: https://github.com/calvinaquino/LNReader-Android/blob/master/app/src/main/java/com/erakk/lnreader/helper/Util.java#L453

**Comment by Mithgol** [comment]
I've decided to close this issue because it gradually loses the first half of its rationale (with the newer Android versions becoming more common and older versions fading out of existence) and has also recently lost the second half of its rationale for me (it would become troublesome to circumvent an official ban of Baka-Tsuki in Russia by using an anonymizing mirror because such mirrors themselves [are to be banned](https://torrentfreak.com/russia-bans-unrestricted-vpns-proxies-and-tor-in-russia-170731/ "TorrentFreak: Russia Bans ‘Uncensored’ VPNs, Proxies and Tor")).

しかたがない！！
