### ISSUE TITLE
I cant download novela nor their images

### ISSUE THREAD

**Issue by a243137** [calvinaquino/LNReader-Android#263]
I downloaded the app and downloaded all the main content I wanted to read, but after I uninstalled the app for space reasons , now that I installed it again I can't download the novels, I can't even see the covers, could anyone help me?

**Comment by a243137** [comment]
Btw whenever I enter a light novel it says "bit map empty"

**Comment by Nandaka** [comment]
Can you open the website from your device browser? What is your android version?
