### ISSUE TITLE
Can't load previews/dowload cover images

### ISSUE THREAD

**Issue by Hi1mBrandon** [calvinaquino/LNReader-Android#265]
I keep getting the following error message;

`
class
javax.net.ssl.SSLHandshakeException
Chain Validation Failed
`

**Comment by Hi1mBrandon** [comment]
Extra info:
While I CAN access the website, doing so brings up the error
`NET::ERR_CERT_DATE_INVALID`

I am running Android 7.1

**Comment by RealDoodler** [comment]
Same problem on a same android and cyanogenmod. I'm using oneplus X

**Comment by Nandaka** [comment]
Looks like you don't have the updated root certificate installed if you also see the error in the browser.

You can try to enable/disable the Load App Keystore in Settings -> Update and Notification on Network section.

**Comment by Hi1mBrandon** [comment]
I didn't really change anything, but it seems to have fixed itself... somehow?

**Comment by Nandaka** [comment]
then mostly it is on the server issue (expired ssl cert?)
