### ISSUE TITLE
Error on watch list

### ISSUE THREAD

**Issue by ruahuy** [calvinaquino/LNReader-Android#269]
After upgrading to latest version on android, i cannot load the watch list anymore and it always comes with this error. I've already reinstall the app but it's the same. Can someone help me ? 
![screenshot_20171005-230646](https://user-images.githubusercontent.com/32549173/31238326-d5e75ce8-aa23-11e7-93f9-58b1573847bd.png)

**Comment by Nandaka** [comment]
Looks like got a bug.

Try to enable ```Quick Load Novel List``` in Settings -> General on Novel Listing section for now.

**Comment by ruahuy** [comment]
It works. Thanks a lot
