### ISSUE TITLE
Can't read any Novels after I deleted it one time.

### ISSUE THREAD

**Issue by OtakuPlayer** [calvinaquino/LNReader-Android#272]
When I Downloaded the app the first time I could read any novel, bur once I deleted it it now won't let me read anything and I tried deleting and installing it again but it still wont let me read instead it shows me this:
"Class
Javax.net.ssl.SSLHandShakeException:
java.security.cert.CertPathValidatorException:
Trust anchor for certification path not found."
Btw my Android version is 7.1.1

**Comment by Nandaka** [comment]
dulplicate with https://github.com/calvinaquino/LNReader-Android/issues/270
