### ISSUE TITLE
Error When Updating

### ISSUE THREAD

**Issue by christantoan** [calvinaquino/LNReader-Android#273]
When trying to update novel info I got this toast message and the info is not renewed
![screenshot_20171206-181020](https://user-images.githubusercontent.com/7300310/33679592-75b28f60-dabf-11e7-9acd-750696d40e9e.png)
I have tried disabling VPN and AdBlock but the problem persists.

**Comment by Nandaka** [comment]
which version do you use? try to disable/enable Use Key Store in Settings --> Update and Notification.

Possible duplicate with #270

**Comment by christantoan** [comment]
I use version 1.1.46 from Play Store.
Thank you. Your solution works.
You're correct. It's a duplicate of #270. Sorry:disappointed:. I didn't find it before.
