### ISSUE TITLE
Error when updating novel info

### ISSUE THREAD

**Issue by ruahuy** [calvinaquino/LNReader-Android#275]
When I tried to update novel info, I got this toast message and the info is not renewed
![screenshot_20171227-102239](https://user-images.githubusercontent.com/32549173/34369703-b4ce4900-eaf0-11e7-9dc1-faf0ef9cf0cf.png)

**Comment by Nandaka** [comment]
Which version do you use? Can you open the website from the phone browser (https://www.baka-tsuki.org/project/index.php?title=Kyoukai_Senjou_no_Horizon)

**Comment by ruahuy** [comment]
I use the android version and I can open the website from phone browser. The other novels get the same problem not just Horizon.

**Comment by ruahuy** [comment]
I use the latest app version.
Disabling Load app keystore do the trick.
Thank you.
