### ISSUE TITLE
Add multithreaded download 

### ISSUE THREAD

**Issue by takase1121** [calvinaquino/LNReader-Android#282]
the download is usually slow as it downloads multiple files. A multithreaded download (download multiple files simultaneously) might help? Please add a option for the number of download threads too if this was added.

**Comment by Nandaka** [comment]
This might be quite tricky as android only allow limited pool of task based on the cpu count (https://stackoverflow.com/a/40823734)
Also, this might cause a problem with concurrent update to DB, maybe paralel download on the novel level, but not down to chapter level.

**Comment by takase1121** [comment]
I see. Thanks for reviewing it anyways!
