### ISSUE TITLE
The latest version doesn't seem to work.

### ISSUE THREAD

**Issue by takase1121** [calvinaquino/LNReader-Android#283]
The latest version from play store seems to error and destroyed my DB. It shows some kind of SQLite error but I forgot to screenshot it before I downgrade to the older version. Please fix this!

**Comment by Nandaka** [comment]
tested on older android, looks like the instr function doesn't exists.

**Comment by Nandaka** [comment]
Try https://github.com/calvinaquino/LNReader-Android/releases/tag/1.1.54

**Comment by takase1121** [comment]
Yes the new release solved the problem. My android is 4.4 and thanks for fixing it!
