### ISSUE TITLE
Watch list error

### ISSUE THREAD

**Issue by jaysonmac** [calvinaquino/LNReader-Android#285]
I can't access my watch list. It just displays a toast about the query error (SQLiteException)
Version: 1.1.54

![screenshot_2018-09-18-22-15-08-352_com erakk lnreader](https://user-images.githubusercontent.com/34416092/45694250-6ee5b500-bb91-11e8-9d0e-2ac868499e36.png)

**Comment by Nandaka** [comment]
what is your android version?

Can you try to go Settings -> General -> on Novel Listing section, enable Quick Load Novel List?

**Comment by Wolfpup67** [comment]
I got the same error. When I tried your suggestion the watched list loaded. My version of Android is 7.1.1

**Comment by jaysonmac** [comment]
The watch list also loaded for me once I enabled Quick Load Novel List
Android Version: 7.0

**Comment by NekoObito** [comment]
This fixed my problem so I closed my issue. Also, at least they got an error. I wasn't even getting an error with mine.
