### ISSUE TITLE
Cannot load downloaded pages from linked projects

### ISSUE THREAD

**Issue by takase1121** [calvinaquino/LNReader-Android#286]
Even if I enabled the 'save external pages' option the reader will attempt to browse the page every time opening it even if the file is present on phone. Please let the reader check for downloaded pages before attempting to load it online.

**Comment by Nandaka** [comment]
it does check the local storage first. Unless the linked pages does redirection, then it may cause detection issue. Which linked page cause the issue?

**Comment by takase1121** [comment]
http://untuned-strings.blogspot.com/2013/10/allison-i-prologue.html?m=1
^ this

**Comment by takase1121** [comment]
I think the page is either AJAX or contains redirection. I can't find the lines of the novel in the file.
Probably thats the cause of the issue.

**Comment by Nandaka** [comment]
Have you tried to wait until the page is fully loaded? I notice it will trigger 2 save event from the toast message. If you load it from offline from the 1st time, I think it will save the blank page.

**Comment by Nandaka** [comment]
Spoke too soon.  Some pages can be saved successfully, some return null
file.  Manual save from menu is working though.

**Comment by takase1121** [comment]
Yes it does save as null even if i try 'save external page' at the reader's menu

**Comment by Nandaka** [comment]
Even after the progress bar is fully loaded? Weird, because I can manually save the page.

**Comment by takase1121** [comment]
yes it saves to when i try 'save external page' when i am reading the novel,but when i try 'download all chapters' in the chapter list, the download complete almost instantly and it is not working too

**Comment by takase1121** [comment]
Tried another linked novels.it also saves to null. BTW i flashed custom rom so my phone is Android 7.1.2 (lineage os 14.1)

**Comment by Nandaka** [comment]
Download All Chapter will not works for linked project. External chapter can only be saved after loaded by the web view manuall (or at least I don't know how to do it automatically to save the html pages + images + css + etc..)

**Comment by takase1121** [comment]
well in my case my old rom with (probably webkit, Android 4.4) webview managed to download it fine but now my webview cant do it (itll always save to null)
